### ISSUE TITLE
Tests that create models make TravisCI red

### ISSUE THREAD

**Issue by dreispt** [OCA/maintainer-quality-tools#104]
This is happening on https://github.com/OCA/server-tools/tree/8.0/base_field_serialized and was found here: https://travis-ci.org/OCA/server-tools/jobs/36851836#L520

The problem is the rule that checks if there are any security access rules missing on new models.
These type of creates create new modules just for testing purposes, but it's it raise the warning on the log, and the current TravisCI checks then report a failure.

How to solve this? Adopt the convention to ignore errors for lines containing `test_model` or `test.model`?

**Comment by pedrobaeza** [comment]
This still applies?
