### ISSUE TITLE
add a dependencies.txt file at repository level

### ISSUE THREAD

**Issue by gurneyalex** [OCA/maintainer-quality-tools#105]
I'm working on the configuration of the runbot for OCA project, and this requires setting up the dependencies of the various projects, a process which is quite tedious, and also related to the writing of `.travis.yml` where such dependencies need to be manually coded. 

I was thinking of a metadata file at the project level describing the inter-repository dependencies which could be used to help in the process. In the simplest form, it would be a plain text file, with 1 repository per line giving the names of the repository on which the current project depends. The scripts launched by travis could be updated so that in case the file is present, they would checkout the listed repository with the  `${VERSION}` branch.  And having this information available would allow for an easier configuration of the runbot (at the moment, I'm grepping for `git clone` lines in `.travis.yml`...)

If people agree with this idea, I'll propose an implementation.

**Comment by gurneyalex** [comment]
related PRs:

* #159: implementation
* OCA/vertical-ngo#107
* OCA/sale-reporting#21
* OCA/purchase-workflow#77
* OCA/l10n-switzerland#77
* OCA/l10n-spain/pull/100
* OCA/l10n-italy/pull/80
* OCA/account-financial-reporting/pull/47
* OCA/l10n-belgium/pull/15
* OCA/connector-interfaces/pull/9
* OCA/department/pull/30

**Comment by pedrobaeza** [comment]
:+1:

**Comment by yvaucher** [comment]
:+1:
