### ISSUE TITLE
[REF] Propose odoo/odoo or oca/odoo branch download with clone

### ISSUE THREAD

**Issue by moylop260** [OCA/maintainer-quality-tools#118]
Hello,
I want to know Why we use a wget to odoo.tar.gz
This generates a bit of complexity in the algorithms of fails.
*Split "/" to get repo and later version in each script that needs it.
  https://github.com/OCA/maintainer-quality-tools/blob/master/travis/test_pylint#L18
  https://github.com/OCA/maintainer-quality-tools/blob/master/travis/test_server#L125
*Process to unzip odoo.tar.gz.
  https://github.com/OCA/maintainer-quality-tools/blob/master/travis/travis_install_nightly#L15

We can simplify this with 
```bash
git clone --depth 1 -b BRANCH ${HOME}/STANDARD_FOLDER
```
And use it directly in other scripts.

NOTE: depth 1 is to get last version without history

**Comment by yvaucher** [comment]
I think we can keep zip file. It excludes completely the `.git` directory. So it should be a bit less data transfered if we compare with `git clone --depth 1`

With clone --depth=1

    $ du .git -sh
    74M     .git

Ok it's really fewer than 588 Mio but it is still bigger than nothing.

**Comment by pedrobaeza** [comment]
@moylop260, do you have then real comparisons about download size/speed? I subjectively think that tar can be faster.
