### ISSUE TITLE
The `type` field is deprecated in the `ir.ui.view` model.

### ISSUE THREAD

**Issue by bwrsandman** [OCA/maintainer-quality-tools#121]
We should fail on deprecation lines such as:
```
2014-10-29 14:32:46,506 23871 WARNING openerp_test openerp.addons.base.ir.ir_ui_view: Setting the `type` field is deprecated in the `ir.ui.view` model.
```

**Comment by llacroix** [comment]
:+1:  Doesn't seem to be done yet.

**Comment by pedrobaeza** [comment]
@moylop260, was this already done?

**Comment by moylop260** [comment]
@pedrobaeza 
This issue is processed by odoo server.
It not supported by pylint-odoo still.

IMHO is a change in log file process.

**Comment by pedrobaeza** [comment]
Yeah, you're right. I think that's too complicated for the benefit get in these new versions, so I close this one.

**Comment by moylop260** [comment]
FYI runbot should show a `warning` (yellow) status in these cases.
