### ISSUE TITLE
UNIT_TEST naming

### ISSUE THREAD

**Issue by lepistone** [OCA/maintainer-quality-tools#124]
I just found out about #90 : an option to test modules separately. I think it is a very good idea in all cases, and I thank you all for making it work.

I'm only a bit concerned about the naming: unit test is something else, this option is about running all the tests of every module separately.

What about renaming it to something like ISOLATE_MODULES or something about that? Keeping the old option for compatibility.

Sorry for arriving late into the discussion, I completely missed #90.

**Comment by pedrobaeza** [comment]
Is this going to be performed?

**Comment by pedrobaeza** [comment]
I close this one, but noted in other issues that talk about UNIT_TEST.
