### ISSUE TITLE
error logging error in test_server

### ISSUE THREAD

**Issue by llacroix** [OCA/maintainer-quality-tools#145]
Not sure but I believe there might be a problem with this line. 
https://github.com/OCA/maintainer-quality-tools/blob/master/travis/test_server#L85

The following line is expecting an object with a key message.

https://github.com/OCA/maintainer-quality-tools/blob/master/travis/test_server#L94

According to this travis error log:
https://travis-ci.org/OCA/knowledge/jobs/41953311

At line 94, it is receiving a string and trying to get a value at index `'message'` but only integers are allowed as index for strings.

**Comment by pedrobaeza** [comment]
This doesn't applied now. Closing.
