### ISSUE TITLE
Use docker and shippable ci to test faster and debug into container

### ISSUE THREAD

**Issue by moylop260** [OCA/maintainer-quality-tools#147]
Hello,
[Docker](https://www.docker.com/whatisdocker/) is a cool tool to run container pre-configured instances from a [dockerfile](https://docs.docker.com/reference/builder/)
Then you can have a instance with your projects just running this file [](https://registry.hub.docker.com/u/vauxoo/odoo-80-image/dockerfile/).
Now there is CI tools to use docker tool as [shippable](http://www.shippable.com/features.html)
IMHO this is a powerful tool to use in OCA.
This will allow:
  Faster test build. Without install depend in each build.
  Debug mode. Run a docker container and run test to local debug.
  Create a new instance from scratch in a few seconds. docker run oca/project

For this we will need next changes:
- [x] Create a organization into docker hub: [oca_org](https://registry.hub.docker.com/repos/ocaimages/)
- [x] Add a script shippable compatibility: https://github.com/OCA/maintainer-quality-tools/pull/151
- [x] Add dockerfile to MQT: https://github.com/OCA/maintainer-quality-tools/pull/152
- [ ] Add OCA members to [oca_org](https://registry.hub.docker.com/repos/ocaimages/)
- [ ] Add to MQT a dockerfile standard with all basic depends installed with depend to ubuntu docker.
- [ ] Each project add a dockerfile with depends to MQT docker but with custom depends.
- [ ] Add a script yml2bash to MQT to run yml files into docker container.
- [ ] Change script to create instance as you would use. (Maybe a folder with ${HOME}/instance/server, ${HOME}/instance/addons/*, ${HOME}/instance/logs)
- [ ] Pay services of shippable to run custom build. Just $12 USD/Year. [Really!](http://www.shippable.com/pricing.html)
- [ ] Pay services of a server of amazon or digital ocean to use [custom-docker](http://blog.shippable.com/dedicated-hosts-) from shippable.

This is the proposal
Can you give us feedback, please?
And knowing who help this hard work.

**Comment by simahawk** [comment]
@moylop260 hi! Just landed here after a google search... this thread is 2 years old: still needed?

**Comment by pedrobaeza** [comment]
I don't think so. With travis2docker, this blueprint is covered. Now we just need to integrate it in our OCA flow, so I close this one.
