### ISSUE TITLE
Add clahub integration

### ISSUE THREAD

**Issue by bwrsandman** [OCA/maintainer-quality-tools#154]
https://www.clahub.com/ is a service for python to make sure all contributors have signed a [Contributor License Agreement](http://odoo-community.org/page/cla)

It adds a line to the Pull requests indicating whether or no the people involved in the PR have signed.

![6-f8092388bfb5188f9d655e09ee2cdc16](https://cloud.githubusercontent.com/assets/1013356/5364630/2e5d19b0-7fb3-11e4-922b-afd4578a9cb7.png)

Thanks to github's update on the 8th of december, it will not overshadow Travis' results.

**Comment by pedrobaeza** [comment]
No need of this now with CLAbot, so I close.
