### ISSUE TITLE
New stable release policy

### ISSUE THREAD

**Issue by dreispt** [OCA/maintainer-quality-tools#156]
**Preamble**

Changes to MQT are sensitive, because they affect all OCA repositories, and more.
Currently the default branch (`master`) is expected to be stable, in the sense that repo maintainers don't except to be surprised by changes that suddenly make every build go red.

Currently, per #86, changes are merged directly into the `master` default branch (used by default in repos), and is up to their maintainers to opt-out from by using a specific stable release instead (currently r1 or r2).

The fact is that does not work well since builds can suddenly go red, either on intended (MQT maintainers decided new checks without repo maintainers knowing or have time to adapt appropriately) or by accident (a change has unexpected consequences).

**Proposal**

I propose to make the latest stable release the default MQT branch, instead of `master`, that could be seen as a *beta* branch. In practice, we would release `r3` now, and make it the default branch.

With this, repos should "opt-in" to using the `master` branch, instead of opt-out to not use it. Some volunteer repos would opt-in and also serve as beta testers, before new stable releases are made.

New stable releases would be proposed with an Issue, but have to be made by a project Owner, since the MQT default branch also needs to be changed (having write permissions is not enough). My suggestion is, as a rule of thumb, do to this every 1 or 2 months, but we don't need a rule for that.

Conservative project maintainers can still use `git -b` to pin a stable release, and decide when to upgrade to the next one.

**Comment by dreispt** [comment]
Anyone interested on more stable MQT releases, or is the current *status quo* OK for everyone?

**Comment by pedrobaeza** [comment]
I think we have dealt correctly with changes in MQT last year after several stabilizations, so I close this one.
