### ISSUE TITLE
Disable Pylint checks on __unported__

### ISSUE THREAD

**Issue by yvaucher** [OCA/maintainer-quality-tools#157]
In https://github.com/OCA/connector-magento/pull/75 I encounter pylint check on `__unported__` dir I don't think we want to check that directory too.

**Comment by moylop260** [comment]
@yvaucher 
Sorry for delay.
I need more information.
Can you give me a build link of travis with problem, please?

**Comment by dreispt** [comment]
I'm not aware of this being an issue right now. I vote to close.

**Comment by pedrobaeza** [comment]
We can `__unported__` to https://github.com/OCA/maintainer-quality-tools/blob/master/travis/cfg/travis_run_pylint.cfg#L3

**Comment by pedrobaeza** [comment]
flake8 check already have it: https://github.com/OCA/maintainer-quality-tools/blob/master/travis/cfg/travis_run_flake8.cfg#L6

**Comment by moylop260** [comment]
@pedrobaeza 
Do you have a travis build where pylint check `__unported__` folder?
pylint don't check paths if not exists a python package (__init__.py in root path).

**Comment by moylop260** [comment]
I found next case:
[travis build with unported checks](https://travis-ci.org/OCA/connector-magento/jobs/44214725)

I saw next folder structure in `__unported__` folder:
![unported](https://cloud.githubusercontent.com/assets/6644187/7655665/b34d13ca-faea-11e4-9684-4bacb4b773a4.png)

I did not know that we added `__init__.py` file to `__unported__` folder.
Is required this structure for you?

**Comment by moylop260** [comment]
I saw this change:
https://github.com/OCA/connector-magento/commit/e8ad2d8fcfa6f4b2945c7e717fd3dad99ceb5d66#diff-68a29d45b5dc96e3451c43107948f08a

I detect next case:
```
File renamed without changes
customize_example/__init__.py → __unported__/__init__.py
```

IMHO this should be:
```
File renamed without changes
customize_example/__init__.py → __unported__/customize_example/__init__.py
```

**Comment by moylop260** [comment]
IMHO this is a expected error of pylint.
I will close this issue.
Feel free to reopen if you consider it necessary.

**Comment by guewen** [comment]
> IMHO this should be:

Of course, it should have been that. It will be corrected once my PR is merged.
