### ISSUE TITLE
Travis broken in repositories when adding OCA as author

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/maintainer-quality-tools#167]
Hi, @gurneyalex, you have broken PEP8 adding OCA as author, because some lines now rebases 80 cols limit. I have seen it in l10n-spain, where I have already fixed it, but the rest of repositories should have the same problem.

**Comment by pedrobaeza** [comment]
Another issue is to put the author without space after comma. I don't know if this is going to be seen akward on apps.odoo.com.

**Comment by gurneyalex** [comment]
I'm working on this. 

Sorry for the inconvenience.
