### ISSUE TITLE
UNITEST setting doesn't raise error

### ISSUE THREAD

**Issue by legalsylvain** [OCA/maintainer-quality-tools#168]
Hi, 

I recently created a repository with 4 modules. When I don't use UNITEST, there is an error because one of the 4 modules depends on an extra repository not set in .travis.yml file. --> Expected error;
In the UNITEST execution, it is marked as success :

https://travis-ci.org/citynox/odoo-extra/jobs/53538518#L302

Module test summary
**Success** google_map
**FAIL** product_cost_incl_bom_qty_3
**Success** agaplan_terms_and_conditions
**Success** mrp_move_direct

+=======================================
| Tests summary:
|---------------------------------------
| test_server Success --> **FAIL Expected**
+=======================================

Kind regards.

**Comment by moylop260** [comment]
@legalsylvain 
This issue is fix it with https://github.com/OCA/maintainer-quality-tools/pull/177
Can you give me your plus one?

**Comment by moylop260** [comment]
Duplicated https://github.com/OCA/maintainer-quality-tools/issues/176
