### ISSUE TITLE
travis container based builds

### ISSUE THREAD

**Issue by gurneyalex** [OCA/maintainer-quality-tools#175]
It would be nice to be able to use Travis container based builds for OCA projects. 

To do this we need to get rid of sudo in our build scripts. 

I've noticed https://github.com/travis-ci/apt-package-whitelist on http://docs.travis-ci.com/user/apt/ and filed the following issues:

* [X] https://github.com/travis-ci/travis-ci/issues/3631 
* [X] https://github.com/travis-ci/travis-ci/issues/3630 

to get python-lxml and expect-dev whitelisted. 

once this is done, we can add these lines in .travis.yml for all projects

    addons:
        apt:
            packages:
                - python-lxml
                - expect-dev

and remove the `sudo apt-get install` commands from our build script.

**Comment by dreispt** [comment]
Is #152 helpful for this?

**Comment by gurneyalex** [comment]
@dreispt no experience with docker, can't really comment on this.

**Comment by dreispt** [comment]
I've been successful at installing and running Odoo without `sudo`, at nirious.io and OpenShift, for example. 
The only trick needed was to remove ldap from the python dependencies, and then a virtualev+pip installation worked.

**Comment by bwrsandman** [comment]
You should be able to just add those two here: https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise

**Comment by bwrsandman** [comment]
I can try adding them and run tests

**Comment by gurneyalex** [comment]
@bwrsandman I made the PRs for the inclusion of the two packages, but I admit I did not even try a PR with the updated .travis.yml to check if it was really needed. Can you do this on one of the OCA projects? If it works, I volunteer to update all the OCA branches with a script as I did to add the `sudo: required` line

**Comment by gurneyalex** [comment]
@meatballhat added the 2 requested packages to the whitelist (thanks!)

I can't work on testing the setup on a repository this week. Will try next week if noone picks this up first.

**Comment by bwrsandman** [comment]
@gurneyalex Update on this?
