### ISSUE TITLE
YAPF

### ISSUE THREAD

**Issue by blaggacao** [OCA/maintainer-quality-tools#185]
[YAPF](https://github.com/google/yapf)

**Comment by dreispt** [comment]
Can you expand your idea, please?

**Comment by blaggacao** [comment]
Yes, of course, citing:
>"Most of the current formatters for Python --- e.g., autopep8, and pep8ify --- are made to remove lint errors from code. This has some obvious limitations. For instance, code that conforms to the PEP 8 guidelines may not be reformatted. But it doesn't mean that the code looks good.

>YAPF takes a different approach. It's based off of 'clang-format', developed by Daniel Jasper. In essence, the algorithm takes the code and reformats it to the best formatting that conforms to the style guide, even if the original code didn't violate the style guide. The idea is also similar to the 'gofmt' tool for the Go programming language: end all holy wars about formatting - if the whole code base of a project is simply piped through YAPF whenever modifications are made, the style remains consistent throughout the project and there's no point arguing about style in every code review.

>The ultimate goal is that the code YAPF produces is as good as the code that a programmer would write if they were following the style guide. It takes away some of the drudgery of maintaining your code."

I think this can be a good idea for tackling the styling war once and for all in the odoo community. OCA is a good place for proposal, I think.

It's kind of the next generation linting machine.

**Comment by dreispt** [comment]
My sentiment is that many times a code style issue is a symptom of a code structure problem.
I'm not against automatic formatting tools, but I'm also fond of them.
Having said that, it could be a candidate tool to include in the maintainer-tools repo.

**Comment by bwrsandman** [comment]
@dreispt I agree with your sentiment, however, it should be noted that automated tools puts the review of style on the shoulders of the commiter and not the reviewer.

This is more important than you might think. If the reviewer no longer needs to review code she is now free to review things like code structure. The more total our automatic style checking can validate our style expectations, the less distracted we are from what really matters such as [best practices](https://www.youtube.com/watch?v=wf-BqAjZb8M).

**Comment by dreispt** [comment]
@bwrsandman Isn't that already the case with current lint checking?

**Comment by bwrsandman** [comment]
It is yes. That can be improved with things like static code analysis such as code climate or codacity.

My point is that reviewing code style is often a deterrent from reviewing the big picture and automated checking / formatting can take this off our shoulders.

**Comment by blaggacao** [comment]
Well, I'm glad, this suggestion was not useless.. In the Go world are also quite good and innovative people, so this is a good reference. Moreover, Google has done many things right, which is another good reference. I would assume knowledgabel people at google have discussed the issue and came up with the conclusion that current tools don't satisfy their needs, so they created this one.

There is an atom.io plugin for this library which automatically reformats everything, can be with live hints or in the end. Sounds good to me.

**Comment by blaggacao** [comment]
ping-pong

**Comment by dreispt** [comment]
Try a PR for OCA/maintainer-tools

**Comment by blaggacao** [comment]
You're right. Unfortunately I'm not capable of realizing my ideas, even though they might be useful at times. :sob:

**Comment by moylop260** [comment]
@blaggacao 
FYI MT has a [autopep8 extended](https://github.com/OCA/maintainer-tools/blob/master/tools/autopep8_extended.py)
In this case, to change snake_case class name to CamelCase.

**Comment by blaggacao** [comment]
Moises, that's cool! Thanks for the hint! 
OT on closed issue: My vision is to have one day a complete OCA development toolset for beginners, because quality code does not always coincide with quality knowledge. The ecosystem needs tools to bridge the gap.. We are working on a dockerized environment and on the OCA prototype module (export xml with a toposort on dependencies) as well as the Odoo - GSpreedSheet connector. But there a spots all around the ecosystem that merit improvement.

**Comment by moylop260** [comment]
Can you help me to try oca-autopep8 with all the active messages?
After that you can generate a ToDo list of refactory code... maybe I can
help to fix it.

**Comment by gustavovalverde** [comment]
Just as a follow up, as using this yapf style seems like a very OCA way of formatting modules:

```ini
[style]
based_on_style = facebook
COALESCE_BRACKETS = True
JOIN_MULTIPLE_LINES = True
ALLOW_MULTILINE_DICTIONARY_KEYS = True
SPLIT_BEFORE_DOT= True
I18N_FUNCTION_CALL = _
```

_This comments does not intend to reopen the issue, but if someone gets here looking for information, this configuration might be helpful_
