### ISSUE TITLE
[IMP] oca_dependencies_apps - Add IMP to process installation of app (apt-get install or pip install)

### ISSUE THREAD

**Issue by moylop260** [OCA/maintainer-quality-tools#188]
I have a project called `parent-project` that depend of `child-project`.
I add next file `parent-project/oca_dependencies.txt`
```txt
child-project
```
This is great! (Thanks for this develop!)

-
However, with same idea we need a new script to install additional dependencies of apps.
e.g.
If `child-project` needs a xsltproc and recaptcha-client apps to work fine then I can add next file:
`child-project/oca_dependencies_apps`
```bash
apt-get install xsltproc
pip install recaptcha-client
```

In `parent-project` I don't need add nothing.
With file `parent-project/oca_dependencies.txt`
```txt
child-project
```
Then child-project dependencies app It will install in `parent-project`

[real case](https://github.com/OCA/maintainer-quality-tools/issues/188#issuecomment-103684524)

Summary task:
- [ ] Add a new file to root project path `oca_dependencies_apt` (file name by define)
    * File to add `apt-get install` packages
- [ ] Add a new file ´requirements.txt´
   * File to add `pip install` packages
- [ ] Add to MQT a recursive process to use all `oca_dependencies.txt`, `oca_dependencies_apt` and `requirements.txt`of each sub-project involved.

**Comment by moylop260** [comment]
An opinion here, please?
We need your feedback to work it in community.

**Comment by dreispt** [comment]
I must admit I didn't understand your proposal.

**Comment by moylop260** [comment]
@dreispt 
Thank for your reply.
I will explain it better.

Currently we use additional scripts to install additional depends:
https://github.com/OCA/connector-magento/blob/8.0/.travis.yml#L23-L24
https://github.com/OCA/account-invoice-reporting/blob/8.0/.travis.yml#L24
https://github.com/OCA/bank-payment/blob/8.0/.travis.yml#L23
https://github.com/OCA/carrier-delivery/blob/8.0/.travis.yml#L24-L25
https://github.com/OCA/report-print-send/blob/8.0/.travis.yml#L21
https://github.com/OCA/runbot-addons/blob/8.0/.travis.yml#L26

We can use a "special" file (maybe called `oca_dependencies_apps`) to install this dependencies automagically.
Imagine that `oca/my-project` depend of `oca/connector-magento`
MQT old version:
You need add to `.travis.yml` file of `oca/my-project`
```yml
  - pip install magento
  - pip install beautifulsoup4
  - git clone oca/connector-magento
  - git clone https://github.com/OCA/connector ${HOME}/connector -b ${VERSION}
  - git clone https://github.com/OCA/connector-ecommerce ${HOME}/connector-ecommerce -b ${VERSION}
  - git clone https://github.com/OCA/sale-workflow ${HOME}/sale-workflow -b ${VERSION}
  - git clone https://github.com/OCA/e-commerce ${HOME}/e-commerce -b ${VERSION}
  - git clone https://github.com/OCA/product-attribute ${HOME}/product-attribute -b ${VERSION}
  - git clone https://github.com/OCA/server-tools ${HOME}/server-tools -b ${VERSION}
```

With current version plus new change in MQT you will need to add:
* `oca/my-project`
  * `oca_dependencies.txt`
      * `connector-magento`

* `oca/connector-magento`
  * `oca_dependencies.txt`
      * `connector`
      * `connector-ecommerce`
      * `sale-workflow`
      * `e-commerce`
      * `product-attribute`
      * `server-tools`
  * `oca_dependencies_apps`
      * `pip install magento && pip install beautifulsoup4`

Please, tell me if I was not very clear

**Comment by pedrobaeza** [comment]
Well, it can be a good idea, but I prefer to call it python_deps, or maybe use standard requirements.txt file.

**Comment by moylop260** [comment]
@pedrobaeza,
Thank for you reply.
requirements.txt file is a good idea for `pip install`

What is your opinion in `apt-get install` case:
https://github.com/OCA/report-print-send/blob/8.0/.travis.yml#L21
https://github.com/OCA/runbot-addons/blob/8.0/.travis.yml#L26

**Comment by pedrobaeza** [comment]
Maybe this can be handled via Travis apt packages (if they are whitelisted).

**Comment by moylop260** [comment]
@pedrobaeza 
Can you explain me `Travis apt packages`case?
As we could install next packages:
 * https://github.com/OCA/report-print-send/blob/8.0/.travis.yml#L21
 * https://github.com/OCA/runbot-addons/blob/8.0/.travis.yml#L26

**Comment by pedrobaeza** [comment]
Here you have the Travis white list: https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise.

If it is included, maybe we can check that section for installing dependencies, or even create environment variables that can be checked.

**Comment by moylop260** [comment]
@pedrobaeza 
Ok, thank for explain me
I searched in [whitelist](https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise) next packages
```
libcups2-dev
cups
```
Used in [report-print-send](https://github.com/OCA/report-print-send/blob/8.0/.travis.yml#L21) and I don't found it

Although it is a good idea, IMHO we should use a idea more generic for all cases.
Including the case that you want it to install an environment locally or enable multi-CI (don't exclusively with travis ci) or use MQT script in a VE or VM.

What do you think?

**Comment by pedrobaeza** [comment]
OK, apart from the two files, we can add also a generic shell script in each repository that can be launched on testing the current repo or when the repo is a dependency.

**Comment by moylop260** [comment]
@pedrobaeza 
+1 with your proposal.

Can you check if I am right in summary (go to final of description in this issue)?

@dreispt,
Can you give us your feedback?

**Comment by dreispt** [comment]
What do you gain on adding the dependencies on a repo file vs adding them directly on `.travis.yml`?

Have a `requirements.txt` sounds good. 
Q1: Do you know if TravisCI processes it automatically?.

Even better is to have MQT look into the module manifests for external dependencies and implemente them. That has the advantage to make clear where the dependencies come from.
Q2: can we still use `apt` in TravisCI container based builds?

**Comment by moylop260** [comment]
@dreispt 
Thanks for your reply.
I will answer you

Q1:
dependencies_app file vs .travis.yml file:

| Feature                  | dependencies_files | .travis.yml |
|--------------------------|------------------|-------------|
| Use recursive            | yes              | no          |
| Use local, VE or VM      | yes              | no          |
| Standard of installation | yes              | no          |

The most productivity is `use recursive`
if I have a main project that depend of 5 other ones I don't need add apt-get sentence of each sub-project.

A real example
[connector-magento](https://github.com/OCA/connector-magento) depend of [connector-ecommerce](https://github.com/OCA/connector-ecommerce)
[connector-ecommerce](https://github.com/OCA/connector-ecommerce) depend of [connector](https://github.com/OCA/connecto), [sale-workflow](https://github.com/OCA/sale-workflow) and [e-commerce](https://github.com/OCA/e-commerce)

Currently you add in [connector-magento](https://github.com/OCA/connector-magento) .travis.yml file the dependencies of [connector-ecommerce] `(good!)`.
But you should not have to add connector-ecommerce dependencies directly  connector-magento
You should be able to avoid this 
[connector-magento-dependecies-1](https://github.com/OCA/connector-magento/blob/8.0/.travis.yml#L25) and [connector-magento-dependecies-2and3](https://github.com/OCA/connector-magento/blob/8.0/.travis.yml#L27-L28)

Because you added this line:
[connector-magento-main-dependency](https://github.com/OCA/connector-magento/blob/8.0/.travis.yml#L26)
And this project has this dependencies:
[connector-ecommerce-dependencies](https://github.com/OCA/connector-ecommerce/blob/8.0/.travis.yml#L24-L26)

MQT should take this dependencies files recursively.

Similar to odoo modules.
You have [web](https://github.com/odoo/odoo/blob/8.0/addons/web/__openerp__.py#L12) module that depend of `base` module.
If you add a [web_api](https://github.com/odoo/odoo/blob/8.0/addons/web_api/__openerp__.py#L10) module that depend of `web` module you don't need add `base` module too.

**Comment by dreispt** [comment]
I didn't fully understand the two last topic in your matrix, but you have a point about recursive system dependencies.
IMO it makes sense that system dependencies should be stated at modules level and not at repo level.

PR #182 already proposes for module inter-dependencies to be handled at module level, instead of the current repo level. It wound not be difficult to extend it to also handle `external_dependencies` keys in modules.

**Comment by moylop260** [comment]
@dreispt 
Thanks for you reply.
Do you have an explanation somewhere of PR #182?

I don't understand `index` files:
[account-analytic.index](https://github.com/dreispt/maintainer-quality-tools/blob/ref-odoo/ooenv/oca-index/account-analytic.index)
With reference to project ifself (account-analytic to account-analytic).

**Comment by dreispt** [comment]
You're right: I was quite laconic.
Index files just map module names to repo URLs where they are hosted.
It could be a single big file, but I found convenient to split it into one per repo.

**Comment by moylop260** [comment]
@dreispt 
Thanks for you reply.
Do you have an explanation somewhere of PR #182?

**Comment by dreispt** [comment]
@moylop260 I added a description at the top of the PR. It also has a link for the `ooenv` project.

**Comment by moylop260** [comment]
I'm thinking in re-use the `external_dependencies` from `__openerp__.py` to generate apt-get and pip install scripts.
But I don't know if is a good idea.

With `external_dependencies` we have extra validation from odoo api for our modules.

You can check this feature [here](https://asciinema.org/a/23098)

**Comment by dreispt** [comment]
@moylop260 IMO it is a good idea.
