### ISSUE TITLE
PEP8 Naming

### ISSUE THREAD

**Issue by bwrsandman** [OCA/maintainer-quality-tools#198]
This should be interesting to add at least to v8 tests https://github.com/flintwork/pep8-naming

I often see reviewers needing to point out lowercase module names.
This should be done automatically to avoid having reviewers review style over substance.

**Comment by bwrsandman** [comment]
Added to #42

**Comment by dreispt** [comment]
:+1:

**Comment by bwrsandman** [comment]
The only thing needed is adding pep8-naming to requirements.txt 
It would fail a large number of builds though, so we should mass fix the namings first on oca-travis

**Comment by dreispt** [comment]
That brings us back to #156 ...

**Comment by pedrobaeza** [comment]
Closing as this is already included in a more general issue.
