### ISSUE TITLE
Test coverage and module initialization code

### ISSUE THREAD

**Issue by dreispt** [OCA/maintainer-quality-tools#206]
Module initialization methods are run when the module is first installed, and not when it is tested.
This makes that code to be marked as not covered ([example](https://coveralls.io/builds/2817711/source?filename=project_stage_state%2Fproject.py#L38)).

To get it covered We could add tests call it, but sometimes this init code shouldn't be run twice.
What would be the best way do deal with this?

**Comment by bwrsandman** [comment]
Perhaps a mock, or perhaps a custom setup and rollback case.

**Comment by dreispt** [comment]
I have an idea: detect and preinstall all core and external dependencies, and then perform the tests on installation (`-i`) of the repo modules to test.
