### ISSUE TITLE
tests are not being executed by default since #186

### ISSUE THREAD

**Issue by lepistone** [OCA/maintainer-quality-tools#213]
See for example the build
- https://travis-ci.org/OCA/purchase-workflow/builds/68473009

the `.travis.yml` does not specify `LINT_CHECK` nor `TESTS`. Since the merge of #186, the default becomes `LINT_CHECK = 1` and `TESTS = 1`, and in that case, surprisingly, no tests are run.

There is probably a quick fix changing that line: 
https://github.com/OCA/maintainer-quality-tools/blob/master/travis/travis_run_tests#L48

We could do that rapidly, I can make a PR for that.

On the other hand, I find that logic a bit confusing because we try to handle too many cases (one action per line, or many) in a very complex way.

- with all defaults to one, the configuration becomes backwards and difficult to follow (for me at least). Specifically, every time we do `SOMETHING = 1` it is actually a no-op
- what actually gets done is not very explicit, because flags interact which each other in ways I find difficult to understand.

Suggestion 1: remove the defaults to one, and remove TESTS altogether (tests are run if there are no other options) so that old repos with a trivial config like purchase-workflow 7.0 still run the tests (no lint, but that is less harmful). example:
```yaml
- 8.0
- 8.0 LINT_CHECK=1
- 8.0 TRANSIFEX=1
```

Suggestion 2: make everything explicit, with no default, (but run everything where there are no variables at all for compatibility)
```yaml
- 8.0 TESTS=1
- 8.0 LINT_CHECK=1
- 8.0 TRANSIFEX=1
```

Thanks to all for your time!

**Comment by guewen** [comment]
Thanks for the details.

I prefer the most explicit one, the suggestion 2. Looks like https://github.com/OCA/connector-magento/blob/8.0/.travis.yml#L12-L18

**Comment by gurneyalex** [comment]
I vote for suggestion 2

**Comment by veloutin** [comment]
```Explicit is better than implicit.```

Perhaps another solution would be to have one variable that specifies what you want to run, instead of 3?

**Comment by dreispt** [comment]
The implicit values were introduced to provide backward compatibility, so that older configs not specifying new directives would still work as expected.
I disagreed at the time with that change, but was alone in that opinion.

But recently TravisCI had significant changes and older configs need to be updated in order to work correctly. Because of this, at this moment solution 2 is an option and IMO is a sensible choice.

**Comment by lepistone** [comment]
@veloutin ah, could be a solution 3. That would make it clear that we do not support many things at the same time.

**Comment by gurneyalex** [comment]
@veloutin @lepistone you mean something like:

 - TRAVISRUN=transifex
 - TRAVISRUN=lint
 - TRAVISRUN=tests

(the name being obviously something to be discussed)

**Comment by veloutin** [comment]
@gurneyalex yes, that's what I meant.

**Comment by moylop260** [comment]
We have many projects with `lint test` and `server tests` enable in same line.
It is a good idea allow me to consider add twices test in a line or a build.
Because We have pay plan and the prices is by build then is better to me make one build.

**Comment by lepistone** [comment]
I see what you mean @moylop260. For lint it is usually useful to split the build, but in other cases (transifex maybe?) it might not make that much sense.

What I would like to get rid of is the defaults to 1 and the magic decisions (most of the `if` in MQT).

Maybe we can keep option 2 or 3, and allow to **explicitly** enable many jobs in the same build.
```yaml
- 8.0 LINT=1 SERVER=1
```
or
```yaml
- 8.0 TRAVISRUN=lint, tests
```

That will require a new release of MQT, a pass in all branches, and we'll do that later. Now I'll try to make a PR for a hotfix, report back here.

**Comment by dreispt** [comment]
I like your second option, to provide a run of actions.
I suggest to keep it lean an use just RUN: `8.0 RUN=lint,tests`

What if we used environment variables with no value set?:

    - 8.0 TESTS
    - 8.0 LINT
    - 8.0 LINT TESTS

**Comment by moylop260** [comment]
I'm happy with a small change:

```diff
--- a/travis/travis_run_tests
+++ b/travis/travis_run_tests
@@ -52,7 +52,7 @@ if __name__ == '__main__':
         tests.append(['test_flake8'])
         tests.append(['test_pylint'])
     # Execute tests by default. Disable them on lint checks
-    if not do_lint_check and do_tests:
+    if do_tests:
         tests.append(['test_server.py'])
     # Execute transifex export with no tests and if it's an official commit
     if not tests and export_transifex and travis_pull_request == "false":
```

**Comment by lepistone** [comment]
@moylop260 I updated #214, it should handle all cases including yours. Please review :sparkles:

**Comment by moylop260** [comment]
@lepistone Ok, thank you!
