### ISSUE TITLE
Transifex builds broken

### ISSUE THREAD

**Issue by dreispt** [OCA/maintainer-quality-tools#218]
Error:

    setup_server() takes exactly 7 arguments (6 given)

Example: https://travis-ci.org/OCA/project-service/jobs/73524670

**Comment by pedrobaeza** [comment]
I have solved directly in https://github.com/OCA/maintainer-quality-tools/commit/1567bfc38cebc0676babe0fb8c541487e9ebd7e8 to avoid more broken commits in the rest of the repos.
