### ISSUE TITLE
ROADMAP: add to description text rendering

### ISSUE THREAD

**Issue by dreispt** [OCA/maintainer-quality-tools#221]
Badly written RST (and MD) can stop the module to be displayed on Odoo form view.
[Example](https://github.com/OCA/web/issues/189).

Solution can be a script using docutils to parse to HTML tested module descriptions.

**Comment by pedrobaeza** [comment]
:+1:

**Comment by yvaucher** [comment]
Good idea :+1:

**Comment by dreispt** [comment]
AFAICR @moylop260 implement this in pylint-odoo. I this we can close.

**Comment by pedrobaeza** [comment]
Indeed it's already implemented. Closing.
