### ISSUE TITLE
Issue when server-tools branch is a dependency of another repo

### ISSUE THREAD

**Issue by guewen** [OCA/maintainer-quality-tools#231]
In oca/server-tools lies a addon called `server_environment`. This addon needs an addon named `server_environment_files` in the addons-path. This addon does not exist in the repo because it has to be created in the user's addons. This is a problem for Travis because it needs this addon to be able to build. This issue has been fixed for the server-tools project (here https://github.com/nbessi/server-tools/commit/d3788534b482471e8c4aed6e75daa7544746b0fa), with a symlink of the sample addon to `server_environment_files`.

Still, as soon as another repository has server-tools in its dependencies, it will ask for `server_environment_files` and as the `ln -s` command is only called in the `.travis.yml` of server-tools the build will fail. An example of a build failing for this reason is the current 8.0 of purchase-workflow: https://travis-ci.org/OCA/purchase-workflow/builds/74869320

What should we do to resolve this problem? 2 ideas below
* Add a `.travis_after_clone.sh` script in the root of the projects that is called when a dependency (or the build's) repository is cloned -> for instance we would have the `ln -s` command in server-tools
* Find another way to fix the `server_environment_files` issue (maybe with a kill-switch in the code of the `server_environment` module based on the Travis environment variables)

**Comment by guewen** [comment]
The real reason why it was failing was that: https://github.com/OCA/server-tools/pull/229#issuecomment-132182372 (`server_environment` loading even when not installed due to the `static` folder). The builds should get green now that oca/server-tools#230 is merged. This question may reappear if a module depends on `server_environment` in another repo though I guess.

**Comment by pedrobaeza** [comment]
Yeah, this is only a workaround I think. I have never understood at all why not putting the folder with the required name (although some people has told their reasonings).
