### ISSUE TITLE
False Error since last commit

### ISSUE THREAD

**Issue by legalsylvain** [OCA/maintainer-quality-tools#245]
Using OCA maintainer quality tools for a custom project, I have Travis errors since today.
https://travis-ci.org/grap/odoo-addons-it/jobs/80231337
openerp file generate W0104 errors today.

I suspect this line : 
https://github.com/OCA/maintainer-quality-tools/commit/f87fd225256d58ea227dca79ef4ab16443c55e21#diff-e10c7dd828886a45ae8d4384a7455e8fR3
from the last commit.

Did you faced the same problem ?

CC : @moylop260, @nhomar.
[V7 Travis Configuration](https://github.com/grap/odoo-addons-it/blob/7.0/.travis.yml)
Kind regards.

**Comment by moylop260** [comment]
Are you using a custom pylint conf?
(reviewing...)

**Comment by legalsylvain** [comment]
No, As said, this is my Travis config file.
https://github.com/grap/odoo-addons-it/blob/7.0/.travis.yml

**Comment by moylop260** [comment]
You will need to add `VERSION="7.0"`
https://github.com/grap/odoo-addons-it/blob/a3fe9eb3553c2ae2092f3769caae940b9ff56729/.travis.yml#L13

**Comment by legalsylvain** [comment]
Thanks, I'm trying your proposal.

**Comment by moylop260** [comment]
You can view .travis.yml template here: https://github.com/OCA/maintainer-quality-tools/blob/master/sample_files/.travis.yml

**Comment by moylop260** [comment]
Thank for reporting.
I will close this issue.
You can feel free to reopen

**Comment by legalsylvain** [comment]
[It works now](https://travis-ci.org/grap/odoo-addons-it/jobs/80239992)
Thanks a lot.

**Comment by moylop260** [comment]
@all 
This error is generated because, now pylint not ignored `__openerp__.py` file, but need of extra plugin with extra params from `VERSION` case.

I can fix this issue but if you don't add `VERSION` you code could be reviewed by lastest guidelines.
Maybe a message "`VERSION` now is required in lint tests" is better.
