### ISSUE TITLE
Coveralls seems to not be working

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/maintainer-quality-tools#247]
In last days, all the PRs I make/review have this state for coveralls: "Coverage pending from Coveralls.io*. Example: https://github.com/OCA/contract/pull/13, but if you access the link, the coverage has been done: https://coveralls.io/builds/3572850.

Does anyone know what's happening?

**Comment by moylop260** [comment]
Do you have the same problem?
There is coveralls.io github project to create a new issue?

**Comment by pedrobaeza** [comment]
It seems the problem is gone, so I close.
