### ISSUE TITLE
[BUG] `INCLUDE=module1` reduce coverage

### ISSUE THREAD

**Issue by moylop260** [OCA/maintainer-quality-tools#249]
Steps:
Project with modules:
  - module1
    - depends: module2,base,sale
  - module2

If I have a .travis with:
`INCLUDE=module1`

Saw:
The method `get_test_dependencies` return base,sale,module2

Expected:
The method `get_test_dependencies` return base,sale

Because pre-install module2 don't execute module2/tests and reduce coverage for this project.

**Comment by moylop260** [comment]
FYI I created this fast patch to fix it:
```diff
diff --git travis/test_server.py travis/test_server.py
index 2b43128..40719d5 100755
--- travis/test_server.py
+++ travis/test_server.py
@@ -254,6 +254,8 @@ def main(argv=None):
     dbtemplate = "openerp_template"
     preinstall_modules = get_test_dependencies(addons_path,
                                                tested_addons_list)
+    preinstall_modules = list(set(preinstall_modules) - set(get_modules(
+        os.environ.get('TRAVIS_BUILD_DIR'))))
     print("Modules to preinstall: %s" % preinstall_modules)
     setup_server(dbtemplate, odoo_unittest, tested_addons, server_path,
                  addons_path, install_options, preinstall_modules)
```

But I think that this should be fix of a better way.

**Comment by pedrobaeza** [comment]
Why is not the best way?

**Comment by moylop260** [comment]
Because I'm using directly environment variable and out of method get_test_dependencies
I need time to refactory very good this issue and create test.
But if anyone want to fix it the help is welcome!

**Comment by pedrobaeza** [comment]
OK, this is out of my scope right now, so I'll wait for your proper solution.
