### ISSUE TITLE
Beta warning when README.rst quotes python code

### ISSUE THREAD

**Issue by clonedagain** [OCA/maintainer-quality-tools#250]
I get the following warning in https://github.com/OCA/stock-logistics-warehouse/pull/81:
`stock_available_sale/__init__.py:1: [E7901(rst-syntax-error), ] RST file README.rst syntax error /home/travis/build/OCA/stock-logistics-warehouse/stock_available_sale/README.rst:16: (WARNING/2) Cannot analyze code. Pygments package not found.`

I suppose that's because the RST contains the following code, which indicates the `code-block` can be interpreted in Python:
```
.. code-block:: python

    if line.product_id and line.product_id.type == 'product' and line.product_id.immediately_usable_qty > line.product_uom_qty:
        failed=True```

**Comment by clonedagain** [comment]
@moylop260 for your information

**Comment by moylop260** [comment]
I got it
Thank you

**Comment by moylop260** [comment]
Fixed!
