### ISSUE TITLE
More and more and more lint checks

### ISSUE THREAD

**Issue by moylop260** [OCA/maintainer-quality-tools#252]
Using pylint-odoo-lint we can add new lint checks.
- [ ] Use  [jshint](http://jshint.com/install/) (javascript linter, in package node)
  - [x] Added to odoolint
- [ ]  Check if button object functions return dicts/ir.actions or a variable
- [ ] Validate basic structure of README.rst with OCA template
- [x] You odoo field string don't need translate method `_` [example](https://github.com/OCA/sale-workflow/pull/213#discussion_r39856737)
  - https://github.com/OCA/maintainer-quality-tools/pull/253
- [x] Deprecated `osv.osv_memory` and `osv.osv`
  - https://github.com/OCA/maintainer-quality-tools/pull/243
- [x] complexity ciclomatic
  - https://github.com/OCA/maintainer-quality-tools/pull/227
- [ ] avoid use of `self.cr.commit` or `self.env.commit` directly (except in tests/)
- [ ] License allowed
  - [x] Added to odoolint
- [ ] Deprecated _fields={}, _defaults={}, (other one?)
  - [x] Added to odoolint
- [x] Use [restructuredtext_lint](https://pypi.python.org/pypi/restructuredtext_lint)
- [ ] pylint enable E0213 - no-self-argument and E0211 - no-method-argument. (If you use empty or not use self in methods of class)
- [ ] pylint enable E1003 - Bad first argument %r given to super()
- [ ] Methods with super expected
 - [x] Added to odoolint
- [ ] <s> list, dict, tuple, with one element per line, append a comma to the last element.</s> too complex
- [ ] Avoid to use yml for test (better use unitest)
- [ ] Missing icon ./static/description/icon.png. (Pending of fix to next issue: https://github.com/odoo/odoo/issues/7507)
- [ ] Documentation ./doc/index.rst (Pending of add first to guidelines)
- [ ] Deprecated `api.one` in v9 and recommended use `api.multi` in v8 more info [odoo/8527](https://github.com/odoo/odoo/pull/8527/files)
  - [x] Added to odoolint
- [ ] Files xml, csv, yml... of openerp without a entry in manifest
- [ ] Files .py without a `import` in `__init__.py` files
- [ ] Use of fields undefined in model
- [ ] Cyclic depends (check before if odoo has this validation)
- [ ] Singular names in name of new modules or clases.
- [ ] Check manifest version format
- [ ] Avoid use of self.assertRaises better use self.assertRaisesRegex to catch exactly message of error
- [x] Add `orm.Model` to deprecated-modules (Considered with openerp.osv deprecated module)
- [ ] Other ideas (python, js, yml, xml, rst, md... all can add a lint)...

**Comment by moylop260** [comment]
> Add orm.Model to deprecated-modules

@dreispt 
What is the `import` line when use `orm.Model`?

**Comment by dreispt** [comment]
`from openerp.osv import fields, orm`

Example: https://github.com/OCA/project/blob/9.0/project_sla/analytic_account.py#L26

**Comment by moylop260** [comment]
@dreispt 
Ok, I got it
The import is the same that we have in deprecated modules [openerp.osv](https://github.com/OCA/maintainer-quality-tools/blob/c7a14d85d85a591999ea4570ca5de93fec46f7b8/travis/cfg/travis_run_pylint_pr.cfg#L78)

Then now is considered too!
Do you want to try it?

**Comment by dreispt** [comment]
OK, I'll look for that in my next push.

**Comment by moylop260** [comment]
Moving this issue to https://github.com/OCA/pylint-odoo/issues/14
