### ISSUE TITLE
Add a requirements.txt

### ISSUE THREAD

**Issue by ajite** [OCA/maintainer-quality-tools#259]
Hi all,

We currently add the list of external python libraries in the `.travis.yml` file so they will be installed during Travis tests [(See here)](https://github.com/OCA/connector-magento/blob/8.0/.travis.yml). 

I think we should add them to a file named `requirements.txt` and install them in Travis with `pip install -i requirements.txt`. It would be more generic that way, and we could use it outside Travis. We need to think how it would work with oca_dependencies.txt.

What do you think? Would it be acceptable?

**Comment by moylop260** [comment]
+1


2015-09-24 11:50 GMT-05:00 Augustin Cisterne-Kaas <notifications@github.com>
:

> Hi all,
>
> We currently add the list of external python libraries in the .travis.yml
> file so they will be installed during Travis tests See here
> <https://github.com/OCA/connector-magento/blob/8.0/.travis.yml>.
>
> I think we should add them to a file named requirements.txt and install
> them in Travis with pip install -I requirements.txt. It would be more
> generic that way, and we could use it outside Travis. We need to think how
> it would work with oca_dependencies.txt.
>
> What do you think? Would it be acceptable?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OCA/maintainer-quality-tools/issues/259>.
>



-- 
Moisés López Calderón
Vauxoo - OpenERP's Gold Partner
Mobile: (+521) 477-752-22-30
Office: (+52) 477-773-33-46
web: http://www.vauxoo.com
twitter: @vauxoo
           @moylop260
hangout: moylop260@vauxoo.com

**Comment by dreispt** [comment]
+1

**Comment by duanyp1991** [comment]
:+1:

**Comment by moylop260** [comment]
Added here https://github.com/OCA/maintainer-quality-tools/pull/311
Enjoy!
