### ISSUE TITLE
[ADD] guideline: Use xpath for `...position=*>` in xml

### ISSUE THREAD

**Issue by moylop260** [OCA/maintainer-quality-tools#262]
Currently we can add a replace with next way:
```xml
<group string="Params" position="after">
```

Odoo now has a new validation:
```bash
  File "./odoo/openerp/models.py", line 1267, in _validate_fields
    raise ValidationError('\n'.join(errors))
ParseError: "Invalid view definition

Error details:
View inheritance may not use attribute 'string' as a selector.
```

Same error with xpath
```xml
<xpath expr="//group[@string='Params']" position="after">
```

The solution is:
```xml
<xpath expr="//group" position="after">
```

or
```xml
<xpath expr="/FULL_XML_TREE/group" position="after">
```

Then xpath is more standard and flexible than `<tag key='value' position="after">`

Should we create a standard of use `xpath` and avoid use `<tag key='value' position="after">`?

**Comment by dreispt** [comment]
No, `<tag key='value' position="after">` should be used whenever possible.

**Comment by pedrobaeza** [comment]
I agree, a good guideline is to provide always a name attribute on each element:
```xml
<group name="group_params" string="Params">
```
so you can do:
```xml
<group name="group_params" position="after">
```

**Comment by flotho** [comment]
And what about the case of overriding an Odoo core module that hasn't got the name in it tag?

**Comment by guewen** [comment]
@flotho one possibility is to look for something that has a name and go down or up from it.
Example, if you have:

```xml

<form>
  <group>
    <field name="name"/>
  </group>
  </group>
    <field name="description"/>
  </group>
</form>
```
And you want to target the second group, you can write
```
//field[@name='description']/..
```
```

**Comment by apps2grow** [comment]
And what about the case of overriding an Odoo core module that hasn't got the name in it tag?
