### ISSUE TITLE
Are Travis-Transifex aware of uninstalled modules?

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/maintainer-quality-tools#266]
This is more a question, and I'm pretty sure that is not an issue, but now that we are going to launch the 9.0 branch creation I want to be sure. Is the travis-transifex script ignoring installable=False modules when exporting to Transifex?

cc @max3903 @Ehtaga

**Comment by sbidoul** [comment]
@pedrobaeza  @max3903 @Ehtaga from a quick code review, I think travis_transifex will ignore uninstallable modules since #263. But I have no way to test that.

**Comment by pedrobaeza** [comment]
Checked that no uninstallable module is exported to Transifex. Closing...
