### ISSUE TITLE
[IMP] clone projects: Create multi pull request builds

### ISSUE THREAD

**Issue by moylop260** [OCA/maintainer-quality-tools#273]
Search in other projects dependency, pull requests with the same branch name of the current branch.

Case of use:
1) I have a project X with oca_dependencies.txt to project Y.
2) I have created pr-x1 to project X with branch name: `featureA`
3) I have created pr-y1 to project Y with branch name: `featureA`
4) pr-x1 depends of pr-y1

Project | oca_dependencies | PR | PR depend | branch dev
--- | --- | --- | --- | ---
y | | pr-y1 | | featureA
x | y | pr-x1 | pr-y1 | featureA

Currently travis build of pr-x1 show errors because use branch stable of project `Y` by default.

We need create the travis build with PR-X1 and PR-Y1 together.

The link to get a relation between PR's is the developer branch name, if is matched with current project then use it instead of stable branch.

**Comment by pedrobaeza** [comment]
This is too complicated to be followed by developers. I prefer to temporally change .travis.yml to point to my branch.

**Comment by moylop260** [comment]
I use dummy PR changing `.travis.yml` too.
IMHO If we use a same branch name in 2 projects then we can avoid dummy PR changing `.travis.yml`

> This is too complicated to be followed by developers.

Are you talking about MQT or use the same developer branch name in 2 projects?

**Comment by pedrobaeza** [comment]
I'm talking about the hidden hints: contributors are not going to follow that convention. They hardly read how to contribute...

**Comment by moylop260** [comment]
Oh you are right!
Note: I don't talking about a new convention, I'm talking about a new feature.
If they want use it: good!
if they don't want use it: good too!

But you and me could avoid reduce PR dummy.

**Comment by pedrobaeza** [comment]
For now I think we can concentrate on another things first, and follow KISS principle here.

**Comment by moylop260** [comment]
Ok, I got it
I will work in our fork.
Thank for you feedback
