### ISSUE TITLE
Duplicate xml record id: false positive

### ISSUE THREAD

**Issue by guewen** [OCA/maintainer-quality-tools#276]
In the new beta pylint checks, I got this line:
```
connector_sync_session/__init__.py:1: [W7902(duplicate-xml-record-id), ] Duplicate xml record id connector_sync_session.group_session_manager
```

In my XML, I intentionally have twice the same xmlid (one in a updatable section and one in a `noupdate` section):

```xml
<?xml version="1.0" encoding="utf-8"?>
<openerp>
  <data>

    <record id="group_session_manager" model="res.groups">
      <field name="name">Synchronization Session Manager</field>
      <field name="comment">The user will have an access to the synchronization sessions.</field>
    </record>

  </data>

  <data noupdate="1">
    <record id="group_session_manager" model="res.groups">
      <field name="users" eval="[(4, ref('base.user_root'))]"/>
    </record>

  </data>
</openerp>
```

So this check can stay as a warning for potential duplicates, but shouldn't raise a red flag for the builds.

**Comment by moylop260** [comment]
@guewen 
Do you have the build where is raised a red flag?

**Comment by moylop260** [comment]
@guewen 
I saw in beta messages next line:
`duplicate-xml-record-id`
https://github.com/OCA/maintainer-quality-tools/blob/1dcb4f3519cd9b2eff0564a6cb2ef7b648c482aa/travis/cfg/travis_run_pylint_beta.cfg#L30

Then this shouldn't raised red maybe is other error that show in same build.
But I need to show the log of build to detect the real error.

Can you help me with the link of travis build?

**Comment by moylop260** [comment]
@guewen 
Fixed here https://github.com/OCA/pylint-odoo/pull/7
Your feedback is welcome!
