### ISSUE TITLE
run_pylint: git error

### ISSUE THREAD

**Issue by gurneyalex** [OCA/maintainer-quality-tools#277]
Facing this weird error in an OCA build: https://travis-ci.org/OCA/partner-contact/jobs/85506783#L174

```
======== Testing test_pylint ========
From https://github.com/OCA/partner-contact
 * branch            8.0        -> FETCH_HEAD
fatal: ambiguous argument 'origin/8.0': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

I'd say the problems comes from `travis.getaddons.get_modules_changed` as it is the only function calling git in the path, but I'm not sure what is intended in this case, or why it is failing.

**Comment by gurneyalex** [comment]
@moylop260 can you look into this please?

**Comment by pedrobaeza** [comment]
or maybe @sbidoul that also makes a change recently

**Comment by dreispt** [comment]
I see in the log line 180 "pylint expected errors 2, found 0!"
But expected errors != from zero should happen only in MQT self tests.

**Comment by moylop260** [comment]
@gurneyalex 
I will review it

**Comment by moylop260** [comment]
The error is because travis clone with
`$ git clone --depth=50 https://github.com/OCA/partner-contact.git OCA/partner-contact`
without `branch` parameter (this should be a travis error because it need last 50 commits with `--depth`).
And now we have new branch `9.0`, then don't found reference to `8.0`

I will fix it

**Comment by moylop260** [comment]
Fixed here: https://github.com/OCA/maintainer-quality-tools/pull/279
