### ISSUE TITLE
Command line tool for local MQT lint checks

### ISSUE THREAD

**Issue by dreispt** [OCA/maintainer-quality-tools#281]
It would be nice for developers to be able to run the MQT lint checks locally, while working on their modules.

So I propose to add a CLI to the lint checks that people can use.
It should have installation instructions and, if possible, instructions to integrate with popular text editors.

**Comment by moylop260** [comment]
+1

**Comment by pedrobaeza** [comment]
This already exists, although not explicitly, here: https://github.com/OCA/maintainer-quality-tools/tree/master/git

**Comment by elicoidal** [comment]
+1
Eric CAUDAL

**Comment by dreispt** [comment]
@pedrobaeza You're right, that's the script. Maybe all we need are some instructions to set it up as a CLI tool.

**Comment by pedrobaeza** [comment]
The instructions are in the README. Go deeper IDE by IDE is not very suitable due to all the possibilities, and this works for all (because they need at the end to commit).

**Comment by dreispt** [comment]
Sorry, Pedro, I'm not finding those instructions. Or are you referring to http://lint.travis-ci.org/ ?

**Comment by pedrobaeza** [comment]
I'm referring to these instructions, that allows to set the pre-commit hook in git: https://github.com/OCA/maintainer-quality-tools/blob/master/git/README.md

**Comment by moylop260** [comment]
Yes, we are using git hook feature.

**Comment by dreispt** [comment]
OK!
