### ISSUE TITLE
Travis Transifex is failing for 9.0 branches

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/maintainer-quality-tools#285]
Or at least, that seems. Please check https://travis-ci.org/OCA/partner-contact/jobs/86581115

@Ehtaga, @max3903 can you please check?

**Comment by yvaucher** [comment]
@pedrobaeza Not sure about that but it failed because it had to create the project on transifex:

    No entry found for host https://www.transifex.com. Creating...

Now it exists

    https://www.transifex.com/oca/OCA-partner-contact-9-0/dashboard/

**Comment by pedrobaeza** [comment]
No, that's the usual behaviour. It creates an entry in local. You can compare it with the same for 8.0: https://travis-ci.org/OCA/partner-contact/jobs/86016030

**Comment by Ehtaga** [comment]
See my answer in: https://github.com/OCA/knowledge/issues/81#issuecomment-163319051

This may be the reason why the script is failing.

**Comment by pedrobaeza** [comment]
From @Ehtaga comments:

> Transifex export script only works for versions 7.0 and 8.0.
> The Odoo connexion classes have only be implemented for those 2 versions.
> Take a look at https://github.com/OCA/maintainer-quality-tools/blob/master/travis/odoo_connection.py

> I didn't have time yet to look into version 9.0, maybe it can use the same connexion process as 8.0, so > you just need to set the context_mapping:
```
context_mapping = {
    "7.0": Odoo7Context,
    "8.0": Odoo8Context,
    "9.0": Odoo8Context,
}
```
> Otherwise an Odoo9Context subclass has to be implemented.

I have added what you says, and it works!, so we can close this issue. Let's see if there's no side effect.
