### ISSUE TITLE
git pre-commit hook doesn't ignore installable=False modules

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/maintainer-quality-tools#286]
@moylop260, is there a way to avoid to check non installable modules?

**Comment by moylop260** [comment]
Oh yes, I have next [pending](https://github.com/OCA/maintainer-quality-tools/pull/263#issuecomment-146379060)

**Comment by moylop260** [comment]
@pedrobaeza
I didn't saw the error that your comment here.
I changed a module to `installable=False` and executed `pre-commit` script
and it wasn't checked.

Could you explain better the real scenario to reproduce the issue?
(git clone, apply change (diff file), commands executed, you saw, you
expected)


-- 
Moisés López Calderón
Vauxoo - OpenERP's Gold Partner
Mobile: (+521) 477-752-22-30
Office: (+52) 477-773-33-46
web: http://www.vauxoo.com
twitter: @vauxoo
           @moylop260
hangout: moylop260@vauxoo.com

**Comment by pedrobaeza** [comment]
It happens on flake8 checks, not pylint, but all unported modules that violate these checks, doesn't allow to continue the commit.

**Comment by moylop260** [comment]
Flake8 dont support just-in-changed and installable=False

**Comment by dreispt** [comment]
Maybe it's time to drop flake8...

**Comment by pedrobaeza** [comment]
I close this one to let #292 as main request for avoiding this.
