### ISSUE TITLE
Tests fail for 9.0

### ISSUE THREAD

**Issue by dreispt** [OCA/maintainer-quality-tools#287]
Setup needs to be updated to support 9.0 requirements, such as lessc.
Example of failed build : https://travis-ci.org/OCA/website/jobs/88802897

**Comment by moylop260** [comment]
FYI [script to install less](https://github.com/Vauxoo/docker-odoo-image/blob/3c23b798ed43315254f4ae248f6fa7827b5adddc/odoo80/Dockerfile#L55-L58)

**Comment by dreispt** [comment]
I have WIP on this...

**Comment by dreispt** [comment]
PR #288

**Comment by pedrobaeza** [comment]
This should be fixed
