### ISSUE TITLE
Drop flake8?

### ISSUE THREAD

**Issue by dreispt** [OCA/maintainer-quality-tools#292]
MQT currently uses two tools for linting, flake8 and pylint, and I see people puzzled at why the complexity.
Indeed this is so for historical reasons (pylint was added only later in the game), but at the moment I feel that pylint is capable of doing everything and more that flake8 can.

So I propose to move the existing flake8 checks to pylint checks, and remove the flake8 dependency from MQT.

**Comment by pedrobaeza** [comment]
If pylint can do everything, why not?

**Comment by moylop260** [comment]
+1

**Comment by elicoidal** [comment]
+1

**Comment by moylop260** [comment]
@dreispt 
Do you have a plan of work in this issue?

**Comment by dreispt** [comment]
@moylop260 I'm sorry but no - in the little time I will have I will give priority to a few new modules I'm in need.

**Comment by moylop260** [comment]
I got it
Thank you.
I will to set the `help wanted` label.

**Comment by pedrobaeza** [comment]
As mentioned in @286, this would also allow to ignore non installable modules.

**Comment by nhomar** [comment]
I was talking with @moylop260 and even pylint team delegate some work to Flake8.

This will be simplified on the move on #500 and future work, can I close this issue?

**Comment by moylop260** [comment]
The pylint’s maintainer recommend us use both tools:
https://github.com/PyCQA/pylint/issues/1110#issuecomment-254527061
