### ISSUE TITLE
Travis fails with OCB + new directory layout

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/maintainer-quality-tools#293]
It seems that the new layout is incompatible with current OCB Travis: https://travis-ci.org/OCA/OCB/builds/89830498

**Comment by pedrobaeza** [comment]
cc @guewen

**Comment by guewen** [comment]
I see. OCB does not call `travis_install_nightly` so `$HOME/dependencies` does not exist. I added a check in #294 that the dependencies path exists before adding it to the addons paths.
