### ISSUE TITLE
crash when a docstring is present in __openerp__.py

### ISSUE THREAD

**Issue by gurneyalex** [OCA/maintainer-quality-tools#295]
This commit https://github.com/OCA/maintainer-quality-tools/commit/d8f265b93039a7f0199dcea3a3b92998db62def6 causes a crash when a docstring is present in __openerp__.py

See: 
https://travis-ci.org/OCA/knowledge/jobs/90332842

(we need to parse in exec mode, not eval).

**Comment by gurneyalex** [comment]
@sbidoul if you have some time, can you look into this? Otherwise I'll try next week.

**Comment by sbidoul** [comment]
@gurneyalex I got the literal_eval thing from Odoo:
https://github.com/odoo/odoo/blob/9.0/openerp/http.py#L1430

Perhaps that particular openerp.py should be adapted?

**Comment by max3903** [comment]
@sbidoul I agree. Closing.

**Comment by max3903** [comment]
http://bugs.python.org/issue25621

**Comment by sbidoul** [comment]
@max3903 I my understanding a string followed by a dict is not a python expression that is supposed to be parseable by ast.literal_eval. 

Adding a docstring at the top of openerp.py makes little sense to me.

**Comment by max3903** [comment]
@sbidoul If we ask Flake8 to test for docstrings, it raises an error.

**Comment by sbidoul** [comment]
@max3903 so let's not test for docstrings in `__openerp__.py`. That docstring could only contain redundant information that is already in the name, summary or description in the same file.

**Comment by max3903** [comment]
@sbidoul if we can skip the docstrings test for `__openerp__.py`, :+1:

**Comment by sbidoul** [comment]
If you ask me, the docstring test can be removed completely.

We already have guidelines leaning towards one class per python file, so in general there is nothing to document at the module level that cannot be documented at the class level, and the module name is generally self-explanatory.

I bet we'll end up mostly with docstring containing zero useful information.

cc/ @moylop260

**Comment by rvalyi** [comment]
@sbidoul :+1:

**Comment by max3903** [comment]
@sbidoul So the docstrings test could be checking the docstrings at the class and method levels, and later on we could generate and publish a technical documentation from them.

**Comment by gurneyalex** [comment]
I agree with @sbidoul 

Should we open a new issue and close this one?

**Comment by moylop260** [comment]
@sbidoul
Im agree with you
The manifest file shouldn't have docstring.
And if we have a class by file we can move the module string to class string.

We should activate class-doc-string in our pylint conf
What do you think?

**Comment by sbidoul** [comment]
@moylop260 even the class-level docstring I'm not sure. I'd think people will always write "extend class" or something similar in the docstring. So maybe not much added value at the class level either. 

Method-level docstring will be helpful, though. So if it's possible to give a warning for missing docstring on methods only (and not for models nor classes) I'd vote for that.

**Comment by moylop260** [comment]
@sbidoul 
Ok I got it
You are right!
If is a inherit class we don't need add a class-level docstring.
(Same case with method-level docstring inherit)

**Comment by gurneyalex** [comment]
I'm not in favor of automating the checking of docstrings on all methods, as this will generate too much noise. 

I'd rather ask for docstring on a per case basis, when code review shows it is required. Otherwise you'll end up with messy docstrings giving no meaningful information

**Comment by sbidoul** [comment]
I completely agree, @gurneyalex

**Comment by rvalyi** [comment]
agree with @gurneyalex

**Comment by max3903** [comment]
so let's close it.
