### ISSUE TITLE
WHTMLtoPDF not setup

### ISSUE THREAD

**Issue by Gimpneek** [OCA/maintainer-quality-tools#301]
Hi,

I'm using OCA/maintainer-quality-tools to test a bunch of modules that use the Odoo/Odoo repo on version 8. 

Tests that use the openerp.tools.test_reports.try_report() method to test the reports I have currently raise an IOError due to the lack of WKHTMLtoPDF on the system. 

Would it be possible to add this to the travis/travis_install_nightly file?

**Comment by pedrobaeza** [comment]
That it's done in the .travis.yml, not in travis_install_nightly. See for example here: https://github.com/OCA/account-financial-reporting/blob/8.0/.travis.yml#L11 and here: https://github.com/OCA/account-financial-reporting/blob/8.0/.travis.yml#L26-L28
