### ISSUE TITLE
Build status is red

### ISSUE THREAD

**Issue by dreispt** [OCA/maintainer-quality-tools#302]
After merging #297.
@moylop260 can you check what might be the cause?

**Comment by moylop260** [comment]
I will review
Thank you

**Comment by dreispt** [comment]
PS: it might have to to with the "expected errors" mechanism.
In fact it has grown to by difficult to manage.
We need evolve to a individual error check, similar to the unittest2 `assertRaises`...

**Comment by moylop260** [comment]
FYI the real error is
https://travis-ci.org/OCA/maintainer-quality-tools/jobs/94179896#L383
`Problem importing module classes.py: cannot import name InferenceContext`

This isn't associated with last commit.
Looks like as library error.
I will verify with travis2docker

**Comment by moylop260** [comment]
I got the error in my local docker:
![pylint](https://cloud.githubusercontent.com/assets/6644187/11506005/1c57f51a-981b-11e5-89a8-9d1fd801591a.png)

Could you give me a moment please?

**Comment by moylop260** [comment]
![fix](https://cloud.githubusercontent.com/assets/6644187/11506267/9280e19c-981c-11e5-9bc8-8b5fdd29a0d3.png)


The issue is by incompatibility  with `astroid==1.4.0`
MQT is compatibility with `astroid==1.3.8`

**Comment by dreispt** [comment]
Thanks for checking this!

**Comment by moylop260** [comment]
FYI fix here:
https://github.com/OCA/pylint-odoo/pull/15

**Comment by moylop260** [comment]
@dreispt 
Thank for report!
