### ISSUE TITLE
Lint - Uses of a deprecated module 'openerp.osv' warning when using openerp.osv.expression

### ISSUE THREAD

**Issue by yvaucher** [OCA/maintainer-quality-tools#306]
If you do

    from openerp.osv import expression

You will get openerp.osv is deprecated on travis pylint test.

Thus I suggest to remove that test

Tests will fail for 

https://github.com/OCA/account-financial-reporting/blob/9.0/mis_builder/models/aep.py#L29
https://github.com/OCA/margin-analysis/blob/9.0/product_price_history/product_price_history.py#L25
https://github.com/OCA/partner-contact/blob/9.0/partner_contact_in_several_companies/models/res_partner.py#L5
https://github.com/OCA/partner-contact/blob/9.0/partner_relations/model/res_partner.py#L24

**Comment by yvaucher** [comment]
This has been reported here: https://odoo-community.org/groups/contributors-15/contributors-27653

**Comment by guewen** [comment]
:+1: for the removal

**Comment by gurneyalex** [comment]
note that you can also use `from openerp.models import expression` (but I'm really not a fan of transitive imports...)

**Comment by Yajo** [comment]
:-1: You just have to change for what @gurneyalex said and pass the lint.

**Comment by moylop260** [comment]
Please, let us know if expresion from models works

**Comment by dreispt** [comment]
AFAIK osv is supposed to be deprecated.
If there is a viable alternative, I don't why we should use it.

**Comment by StefanRijnhart** [comment]
Can't the test be made more sophisticated so as to exclude expression?

**Comment by moylop260** [comment]
> @StefanRijnhart 
Can't the test be made more sophisticated so as to exclude expression?

let me try it with [augmentations](https://github.com/OCA/pylint-odoo/blob/master/pylint_odoo/augmentations/main.py#L18)

**Comment by moylop260** [comment]
FYI the fix https://github.com/OCA/pylint-odoo/pull/40
