### ISSUE TITLE
No coveralls in 9.0 builds

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/maintainer-quality-tools#321]
It seems that there's no coveralls check on 9.0 builds. Example: https://github.com/OCA/partner-contact/pull/253

Somebody knows why?

**Comment by moylop260** [comment]
The coveralls was created
https://coveralls.io/jobs/12714088
But they was a downtime for maintaining

Could you try with a rebuild again, please?

**Comment by pedrobaeza** [comment]
Thanks for the info. I close this.
