### ISSUE TITLE
Package version mismatch

### ISSUE THREAD

**Issue by zeroincombenze** [OCA/maintainer-quality-tools#324]
Hello,
I am a bit confused: how to work MQT on Odoo 9.0?
MQT requires pyparsing version < 2 rather Odoo 9.0 requires pyparing 2.0.3
and
MQT requires python-dateutil < 2 rather Odoo 9.0 requires python-dateutil 2.4.0
I saw other version mismatch too.

Hope this help

**Comment by moylop260** [comment]
Currently, MQT use a [requirements.txt](https://github.com/Vauxoo/maintainer-quality-tools/blob/master/travis/requirements.txt)
But if you wish change or add a new one you can add a custom requirements.txt in your project.

Or if you consider that we should use a requirements.txt by version should be a good approach.

**Comment by zeroincombenze** [comment]
Thanks for you answer.
The trouble borns by requirements.txt of MQT and Odoo. 
So if you change requitements.txt of MQT you do not meet Odoo 9.0 requirements.
If you change requitements.txt of Odoo you do not meet MQT requirements.
What you consider the best approach?

**Comment by moylop260** [comment]
That is a good approach.
MQT currently is adapted for travis, then travis use a packages custom install... and this one is removed from `mqt/requirements.txt`

Maybe we can use `sed` command to odoo original `requirements.txt` to adapt it for travis.

**Comment by zeroincombenze** [comment]
Please look at 
https://github.com/OCA/maintainer-quality-tools/blob/master/travis/requirements.txt
and 
https://github.com/OCA/OCB/blob/9.0/requirements.txt
I ask me if this mismatch could be met in Odoo 9.0 testing, now of in future

Again
If a user would test Odoo 9.0 and Odoo 8.0 on the same machine, meets different requirements.

Thanks

**Comment by lepistone** [comment]
Hi, I checked the specific cases of `pyparsing` and `python-dateutil`. Both of them made python 3-only releases at some point (`pyparsing` 2.0.0 and `dateutil` 2.0), But then they made later releases that support both python 2 and 3. I think in our `requirements.txt` we could just exclude those two python3-only versions with `!=` (see https://pip.pypa.io/en/stable/reference/pip_install/#example-requirements-file). 

Thanks!

**Comment by pedrobaeza** [comment]
Solved in https://github.com/OCA/maintainer-quality-tools/commit/03d026651500a4c01fb4aa45792c7f6f6e589625
