### ISSUE TITLE
E731 do not assign a lambda expression, use a def

### ISSUE THREAD

**Issue by dreispt** [OCA/maintainer-quality-tools#332]
I was just bitten by this check at https://travis-ci.org/OCA/server-tools/jobs/133389301#L422
Assigning a lambda to a variable is perfectly correct practice.
It can be used, for example, to use a more readable alias for a longer expression, thus making code more readable, or to as a more readable alternative to build a Partial function.

I don't see the point for this check.

**Comment by moylop260** [comment]
A point important is that our configuration file of flake8 has `disable` checks instead of `enable` checks and dont have a specific version to install.

Then the new checks are visualized with a new version of flake8 when you run a re-build.

I dont know if this is a expected behaviour but IMHO the version of flake8 should be freeze and the checks should be `enabled` instead of `disabled` like as pylint.

**Comment by lepistone** [comment]
This comes from pep8.

I went to check your example: 

```python
upgrade = lambda self, value, args, offset=0, limit=None, \
    order=None, count=False: value if count else self.browse(value)
```

In your case I would personally use a def like pep8 suggests. The backslash is maybe I sign that it is a bit too long for a lambda?

Still, I think this is up to taste and your code looks good to me. So I'm ok for disabling the check if you like.

**Comment by lepistone** [comment]
Since this check comes from pep8 itself, I have a small preference to keep it (I prefer not to add exceptions if there is not a strong reason).

**Comment by dreispt** [comment]
@moylop260 Thanks for the explanation.

For the particular usage, I was just trying to fit [Odoo core code](https://github.com/odoo/odoo/blob/8.0/openerp/models.py#L1629) into the 80 col limit. 
Alternative suggestions are welcome.

On the generic topic, I've seen smart usage of lambdas as shortcuts for expressions or partial functions, making the code more concise and readable. So I lean to allowing them.

**Comment by dreispt** [comment]
I'm curious. PEP8 states as a "Programming Recommendation":

> Yes:
> def f(x): return 2*x
> 
> No:
> f = lambda x: 2*x
> 

But isn't the suggested form invalid PEP8?

**Comment by lepistone** [comment]
It looked invalid to me too, but apparently the return on the same line is OK (I didn't find a rule against it).

As I said I find this subjective, but I'm just curious about what you mean by "smart usage ... as shortcuts"...

In your case, what's wrong with an inner `def` ?

```python
def upgrade(self, value, args, offset=0, limit=None, order=None, count=False):
    return value if count else self.browse(value)
```

 It isn't really longer. Also there are many parameters, some with default values, and a decision (`if`). It doesn't look like trivial code to me.

**Comment by dreispt** [comment]
Let's leave at it is, and I'm changing the code on my module. 

About the "smart use", a quick example:
Consider:

    def mult(x, y):
        return x*y 

The double could be defined as:

    double = lambda x: mult(x ,2)
    print double(5)

Much more concise than:

    def double(x):
        return x*2
    
    print double(5)

This particular example probably doesn't look neither too convincing nor too exciting, but I can't find nothing short and effective right now :disappointed:
