### ISSUE TITLE
UNIT_TESTS do nothing

### ISSUE THREAD

**Issue by dreispt** [OCA/maintainer-quality-tools#333]
No actual tests are ran.
Example: https://travis-ci.org/OCA/server-tools/jobs/134704190#L329

This is not a liked feature, so maybe it's time it is deprecated. Thoughts?

**Comment by lepistone** [comment]
Thanks! If it's broken, let's remove it.

**Comment by lmignon** [comment]
:+1: to remove it.

**Comment by moylop260** [comment]
What about the following proposal https://github.com/OCA/maintainer-quality-tools/issues/251#issuecomment-157998116?

**Comment by dreispt** [comment]
@moylop260 Sounds good. We can do both.

**Comment by pedrobaeza** [comment]
Any advance in this?
