### ISSUE TITLE
TravisCI failing on the fork branch builds 

### ISSUE THREAD

**Issue by dreispt** [OCA/maintainer-quality-tools#334]
The build is correct, but it error on the fork branch because of Transifex.
Exanmple: https://travis-ci.org/dreispt/server-tools/builds/135384545

**Comment by moylop260** [comment]
It's is a expected behaviour of travis in the [documentation](https://docs.travis-ci.com/user/environment-variables/#Encrypted-Variables)

You could try use your own [encrypted variables for transifex](https://github.com/OCA/maintainer-quality-tools/blob/master/sample_files/.travis.yml#L36-L52)

**Comment by dreispt** [comment]
I don't think that's a solution.
Transifex should only run on a merge with the OCA branch.

**Comment by moylop260** [comment]
Please, review https://github.com/OCA/maintainer-quality-tools/pull/340

**Comment by lasley** [comment]
I'd say we're probably good here - my forks have been nice and 💚  since the fix. You seeing the same @dreispt ?

**Comment by dreispt** [comment]
#340 is merged, I think this is solved. Closing.
