### ISSUE TITLE
Add ESLint to the bots

### ISSUE THREAD

**Issue by Yajo** [OCA/maintainer-quality-tools#344]
JS code is not getting style-checked at all. [ESLint seems the best choice among JS linters](https://www.sitepoint.com/comparison-javascript-linting-tools/), so it would be nice to have a green mark for it at PRs.

**Comment by moylop260** [comment]
Currently we have a [js-lint](https://github.com/OCA/pylint-odoo/blob/e19267d7e6ebe05e47f087f74e7e7de7b5c64fcb/pylint_odoo/misc.py#L141-L146) integrated with [OCA/pylint-odoo](https://github.com/OCA/pylint-odoo)

You can see the following examples of the output:
 - https://github.com/OCA/l10n-brazil/pull/308#issuecomment-219663898 
 - https://github.com/OCA/account-financial-reporting/pull/189#issuecomment-219645638

Is the proposal of this issue or im missing something?

**Comment by Yajo** [comment]
Oh I did not know. 

Then it would be nice to include the config file in repos to make IDE plugins autocheck.

**Comment by Yajo** [comment]
... if jshint allows that

**Comment by moylop260** [comment]
Im working on a global configuration file for oca
https://github.com/OCA/pylint-odoo/pull/49

But we can change it from local.

But we have very few followers to pylint-odoo and I dont have enough plus one...

We could be happy if you help us with feedback and if you follow the project.

We can discuss the new features in the other project.

For now, I close this issue.

**Comment by moylop260** [comment]
@Yajo 
FYI I like http://eslint.org/docs/rules/ 
It has a check to disable `console` and other ones.
JSLint (currently used) https://github.com/jshint/jshint/issues/2979#issuecomment-232479489 I can't added it

I will change our js lint from pylint-odoo.
Thanks for the information.

**Comment by Yajo** [comment]
Nice to hear! Then [adding a `.eslintrc.yml` file to each repo](http://eslint.org/docs/user-guide/configuring#configuration-file-formats) would make all ESLint-enabled IDEs work magically!

**Comment by Yajo** [comment]
A sample one, in case it helps:

```
env:
    browser: true
    es6: true
globals:
    odoo: true
extends: 'eslint:recommended'
parserOptions:
    sourceType: module
rules:
    comma-dangle:
        - warn
        - only-multiline
    indent:
        - error
        - 4
    linebreak-style:
        - error
        - unix
    semi:
        - error
        - always
```

**Comment by moylop260** [comment]
To start we can use a global configuration file in your $HOME
If a checker is very particular for a project and just for a project we can add it a custom configuration file (Before discard that isn't a global check)

Note: I don't have a example where a checker is just for a particular project.

Otherwise maybe we could use the git-hook script to generate in your local.

To start I don't image a custom configuration file by each project.

**Comment by Yajo** [comment]
well of course we can, it is only to let everyone share the same warnings and errors in their linters magically. Problem is OCA has a bunch of repos. If at least OCA provides their own file wherever, I could copy it to my HOME.

**Comment by dreispt** [comment]
(OT) For extra fun, rename this Issue to "Feed ESLint to the bots" 😸
