### ISSUE TITLE
Travis is green on catastrophic failures

### ISSUE THREAD

**Issue by lasley** [OCA/maintainer-quality-tools#348]
When there is a catastrophic issue with core, such as an ImportError, Travis is displaying a false green. I believe this is because the test runner isn't actually initialized yet, so we don't have any output.

Example - https://travis-ci.org/laslabs/odoo-connector-carepoint/jobs/157901951#L983

I'm assuming Odoo is throwing an exit code, I wonder if it would be possible to catch this and fail if anything other than a `0`?

**Comment by osvalr** [comment]
@lasley I confirm this is happening.

**Comment by moylop260** [comment]
Maybe is time to use the regex of runbot to detect errors on logs https://github.com/odoo/odoo-extra/blob/8.0/runbot/runbot.py#L42

**Comment by lasley** [comment]
@moylop260 - I feel like the existing regex is accomplishing the same thing though, just with more options. It's definitely syntactically the same.

I took a look at the code, and I'm pretty sure it's because we are only listening for `CRITICAL` log level on versions >7. All of my samples are failing with an `ERROR` log level.

I proposed a fix in #352 but I have no idea how to test it. Can you point me in a direction?

**Comment by pedrobaeza** [comment]
Closing this as there's an ongoing PR
