### ISSUE TITLE
Clone OCA dependencies

### ISSUE THREAD

**Issue by angelmoya** [OCA/maintainer-quality-tools#349]
I don't know if it could be a bug, check this PR

https://github.com/OCA/website/pull/253

In website repository I add OCA dependecy for event repository:

https://github.com/angelmoya/website/blob/ADD_website_event_registration_seat_limit/oca_dependencies.txt

But is not working

**Comment by moylop260** [comment]
I re-build the builds because is a problem with github delay or travis internet...


We hope that the rebuild fix them

**Comment by angelmoya** [comment]
Thanks @moylop260 , travis is working, I rebuild runbot but it failed

**Comment by moylop260** [comment]
Check my last comment from your PR
By now I close this issue
