### ISSUE TITLE
Fix test coverage measurement

### ISSUE THREAD

**Issue by dreispt** [OCA/maintainer-quality-tools#35]
The current use of `coveralls` used in PR #29 is meaningless for shell scripts.
Would it be better to remove it?
Or perhaps add shell test coverage checking using [shcov](https://code.google.com/p/shcov/) or similar.

**Comment by bwrsandman** [comment]
We have converted a lot of the scripts to python, I think now is a good time to re-activate coveralls

**Comment by moylop260** [comment]
@dreispt 
Can we close this issue?
