### ISSUE TITLE
outdated transifex-client

### ISSUE THREAD

**Issue by gurneyalex** [OCA/maintainer-quality-tools#350]
Here's a mail I received from Transifex:

Hi OCA Transbot,
We noticed that recently you used an outdated version (0.11b3) of the client to access Transifex.com. If you would like to take advantage of all the new features that have been implemented in the newer versions, you can visit http://bit.ly/tx-client-install for instructions on how to install the latest one. For any questions you may have, feel free to contact us at https://www.transifex.com/contact/.

**Comment by dreispt** [comment]
Looks like the Transifex client version is [pinned](https://github.com/OCA/maintainer-quality-tools/blob/master/travis/requirements.txt#L32).

**Comment by pedrobaeza** [comment]
Maybe it was due to any problem with later versions. We can just try...

**Comment by pedrobaeza** [comment]
Unfortunately, it's not documented what is the reason...

**Comment by sbidoul** [comment]
I propose to unpin it before the week-end run. Does anyone anticipate a particular risk?

**Comment by pedrobaeza** [comment]
Nop when I tried, but Maxime did the tests on OCA's machine and maybe he found a problem. Perhaps you can make a live test running manually the script.

**Comment by sbidoul** [comment]
@max3903 any advice here? I can do the change on the OCA server.

**Comment by pedrobaeza** [comment]
I suppose this is already done, isn't it?

**Comment by pedrobaeza** [comment]
@sbidoul did you update this?

**Comment by pedrobaeza** [comment]
I have found the problem investigating #370, and I have updated it in https://github.com/OCA/maintainer-quality-tools/commit/648a438f719c6dfda9b5df128481500f93a6aadc, so I close this one
