### ISSUE TITLE
ImportError: No module named click

### ISSUE THREAD

**Issue by simahawk** [OCA/maintainer-quality-tools#356]
If you try to run `travis/run_pylint.py`

**Comment by simahawk** [comment]
@nhomar move your a**!

**Comment by moylop260** [comment]
Could you try install:  `pipi install pylint-odoo` in orde to fix it?
(its is locally, rigth?)

**Comment by pedrobaeza** [comment]
If pylint-odoo is not in the requirements.txt of MQT, then the error is correct.

**Comment by moylop260** [comment]
WIP from https://github.com/OCA/maintainer-quality-tools/pull/500
