### ISSUE TITLE
FYI: support for 10.0+

### ISSUE THREAD

**Issue by yelizariev** [OCA/maintainer-quality-tools#362]
Possible solution is here

https://github.com/it-projects-llc/maintainer-quality-tools/blob/96972f7/travis/travis_install_nightly#L47

**Comment by moylop260** [comment]
Do you have planned create a new PR?

**Comment by yelizariev** [comment]
No, I am not sure that maintainers of this repo approve my approach. 
Also, OCA still doesn't have 10.0 branches.

Feel free to take my idea and create new PR/

**Comment by yelizariev** [comment]
Fixed version:

https://github.com/it-projects-llc/maintainer-quality-tools/blob/master/travis/travis_install_nightly#L47

    [[ -f ${HOME}/${REPO[1]}-${VERSION}/openerp-server ]] || ln -s odoo-bin ${HOME}/${REPO[1]}-${VERSION}/openerp-server

**Comment by StefanRijnhart** [comment]
Thank you for the suggestion. We will try https://github.com/OCA/maintainer-quality-tools/pull/364
