### ISSUE TITLE
MQT should check the addon version structure

### ISSUE THREAD

**Issue by sbidoul** [OCA/maintainer-quality-tools#366]
A PR should be red if the version number does not match `<series (7.0|8.0|9.0|10.0)>.<major>.<minor>.<patch>`

@moylop260 do you think you can easily enable this?

**Comment by moylop260** [comment]
Sound good to me
In he past we don't have this validation because I don't found a solution to add new versions automatically.
Then we will need to add new version of odoo manually in each release (IMHO bad idea)

**Comment by sbidoul** [comment]
@moylop260 putting the check on the version structure in place is one thing that should be doable right now.

Then enforcing some version change policy is another, independent, much more complex topic.

**Comment by moylop260** [comment]
Currently we are checking the format with a regex

`\d+.\d+.\d+.\d+.\d+`
I mean
 - odoo version (2 numbers separated by dot)
   E.g. 8.0
 - major.minor.patch (3 number spearated by dot)
  E.g. 1.0.1

But we don't have a strict odoo version validation.
(8.0|9.0|1.0)\d+.d+.\d+

If you are talking about the first case the check currently exists: manifest-version-format

**Comment by pedrobaeza** [comment]
Better to put also the second one. When migrating, people forget to change series version

**Comment by sbidoul** [comment]
Yes, both checks please, as errors. 

All repos are clean now but I had to spend some time again to fix many version numbers.

**Comment by moylop260** [comment]
Ok
The second one is good to me.
And if is good for you add manually the update in each odoo release then lets to do it

**Comment by pedrobaeza** [comment]
The check shouldn't be done on non installable modules. We can include in the branch migration script next time the automatic series change also (as we did with the manifest renaming).

**Comment by moylop260** [comment]
FYI https://github.com/OCA/pylint-odoo/pull/77/files
