### ISSUE TITLE
Translations in Transifex are overwritten

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/maintainer-quality-tools#370]
If you make some translations on Transifex and there's a push in the repository before making Transifex > GitHub synchronization, terms are overwritten. I'm investigating how to solve it. I will need to make several direct commits to try this, as PRs are not taking into account.

**Comment by pedrobaeza** [comment]
I continue checking how to solve this.

Meanwhile, @sbidoul, can you please update maintainer-tools in the server that runs oca-tx-pull to save some requests for avoiding limit rate that I have committed in https://github.com/OCA/maintainer-tools/commit/f866401a7e015c31847f2ae78813619ecbdfbee2

**Comment by sbidoul** [comment]
@pedrobaeza done.

**Comment by pedrobaeza** [comment]
Already fixed in https://github.com/OCA/maintainer-quality-tools/commit/4cad6e57feaabfb805a9c7972ac8b8c53924d9b9
