### ISSUE TITLE
Transifex passes with invalid secure token

### ISSUE THREAD

**Issue by lasley** [OCA/maintainer-quality-tools#373]
We noticed in OCA/infrastructure-dns#7 that [Transifex is passing in Travis](https://travis-ci.org/OCA/infrastructure-dns/jobs/166807051) when the [secure is invalid](https://github.com/OCA/infrastructure-dns/pull/7/commits/bb41855fb3ffb62a14485c2418a1b9d5a3a49554).

Unfortunately the only bit of Transifex I know is that it exists, so I'm not of much use here other than as a debug dummy 😑

**Comment by nhomar** [comment]
I think transifex isnot used anymore.

closing.

**Comment by pedrobaeza** [comment]
Well, it's still used as Weblate can't fully replace it yet, but it's expected to work soon, so let's keep it closed.
