### ISSUE TITLE
False positive about missing external dependency

### ISSUE THREAD

**Issue by gurneyalex** [OCA/maintainer-quality-tools#374]
I'm wondering about this pylint error https://travis-ci.org/gurneyalex/server-tools/jobs/167569993#L297

psutil is a dependency of odoo core (https://github.com/odoo/odoo/blob/8.0/requirements.txt#L20), so in my opinion we should not require its declaration in the dependencies of the addon.

**Comment by gurneyalex** [comment]
@moylop260 @pedrobaeza @dreispt your input on this is very welcome.

**Comment by moylop260** [comment]
Thanks
You are right!

FYI  the libraries was extracted from `import` sentences, but the nested imported was ignored.
We have a import of [psutils with try except](https://github.com/odoo/odoo/blob/d81258ab8e0dcb6c0df3a47ab8084ec99b7d3e24/openerp/http.py#L40-L43)

I will added in the whitelist from pylint-odoo and I review other similar cases.

**Comment by moylop260** [comment]
FYI fix https://github.com/OCA/pylint-odoo/pull/78

**Comment by gurneyalex** [comment]
thanks @moylop260 (and @pedrobaeza)
