### ISSUE TITLE
Force increase addon version

### ISSUE THREAD

**Issue by Yajo** [OCA/maintainer-quality-tools#376]
It would be nice to have a check that enforces version number increments on PRs, [according to guidelines](https://github.com/OCA/maintainer-tools/blob/master/CONTRIBUTING.md#version-numbers).

So, every patch that has no version increment gets :x:.

The rationale behind this is that I'm thinking of some sort of autoupdate addon that updates all addons whose current version does not match the currently installed one. Kinda "update all", but only what is needed and automatically, to get less failures in case an addon gets updated.

**Comment by moylop260** [comment]
This issue is duplicated https://github.com/OCA/pylint-odoo/issues/59
Lets to followup from other one

**Comment by Yajo** [comment]
I knew somebody else must had thought on this before :grin:

**Comment by moylop260** [comment]
@jjscarafia
Maybe you could add here the link of your module that auto-update from version information
