### ISSUE TITLE
[blueprint] Allow to co-test other repositories, enabling Satellite and Integration repos

### ISSUE THREAD

**Issue by dreispt** [OCA/maintainer-quality-tools#378]
There a trend to split big topic repos into smaller and more focused ones. 
This is expected to allow for maintainers to have more focus, ownership and accountability.
A disadvantage, compared to the large topic repos, is that this adds fragmentation of the code: it is harder to find modules based on the topic area, and we lose the integration tests of the modules on the same topic, making it easier for incompatibilities to creep in.

A possible solution for these disadvantages is to have both worlds: more of these maitainer driven "satellite repos", and at the same time large "integration repos", where all the satellite repos are joined together, for better discoverability, for integration tests, and for better overseeing of the corresponding PSC.

To enable this, I propose the "cotest" MQT feature: repos can have a list of other repos to be tested along with the repo modules. This might be enabled only for specific builds.
The feature can be used both on the Sattelite repos and on the Integration repo.

**Comment by moylop260** [comment]
I have a similar issue with [vauxoo/addons-vauxoo](https://github.com/vauxoo/addons-vauxoo)
I need test addons-vauxoo from other projects like as [vauxoo/forecast](https://github.com/Vauxoo/forecast)

Then I need include in the test the modules of addons-vauxoo from forecast project.
Including the coverage of the modules dependency of other projects.

I worked here:
https://github.com/Vauxoo/maintainer-quality-tools/pull/44/files#diff-4b42f344199e5694ffee3d2a57dd80c7R228

I don't know if is the same but I'm happy if somebody help us with extract the change to OCA/mqt

**Comment by nhomar** [comment]
I will close this and re-open it when this will be worked, @moylop260 @dreispt what do you think?
