### ISSUE TITLE
[discussion] Be more portable / travis-agnositc

### ISSUE THREAD

**Issue by blaggacao** [OCA/maintainer-quality-tools#379]
Travis is a great tool and probably has most wide adoption among open source projects. It does the job really good and is the commonly accepted standard.

Some people are working with other Ci services or even utilize a different approach (such as Gitlab's integrated workflow, which goes from SVC capabilities, to CI capabilities and is embracing deployment at the moment).

It would undoubtedly beneficial to those people if it would be easier to use parts of the MQT code for their system of choice. While I understand that this is a special purpose repository with a well defined use case, it definitely has it's "gray" use cases outside the OCA github realm. Making this tool more versatile might still be inline with the idea and general purpose of the OCA. and be a legitimate goal.

What (hypothetically) can and what (hypothetically) needs to be done in order to achieve this? Are (subjectively) the costs too high?

**Comment by blaggacao** [comment]
Here is some code to look at: https://github.com/OCA/maintainer-quality-tools/pull/380
I guess this kind of idempotent changes could be a nice start, not sure if this is even all of it. Having a more neutral naming scheme reminds later developments to keep a clear and well defined interface in mind.

**Comment by nhomar** [comment]
It is being faced here:

#500 

And an example for gitlab with the current state is here:

#501

**Comment by nhomar** [comment]
BTW @blaggacao part of your work here #380 will be reviewed to be included in one way or another here #500 sorry for the delay several discussions around this have taken and we are trying to move forward, your comments has been helpful also.
