### ISSUE TITLE
New env vars suggestion

### ISSUE THREAD

**Issue by jjscarafia** [OCA/maintainer-quality-tools#383]
After talking with Moises we have raised in too this suggestion to add some more variables to travis that are used in different environments (template, test, run)

### Already existing variables:
- SERVER_OPTIONS: affects template, test, run
- INSTALL_OPTIONS: affects test

### New variables:
- RUN_OPTIONS: affects run
- INSTALL_OPTIONS_EXTRA, SERVER_OPTIONS_EXTRA and RUN_OPTIONS_EXTRA: to be used, for eg, in runbot_travis2docker to add custom options

### Builds would be:
```
# -d openerp_template -i modules_dependencies $INSTALL_OPTIONS $INSTALL_OPTIONS_EXTRA $SERVER_OPTIONS $SERVER_OPTIONS_EXTRA
INSTALL_OPTIONS
INSTALL_OPTIONS_EXTRA
```

```
# -d openerp_test -i modules_to_test --test-enable $OPTIONS $OPTIONS_EXTRA $SERVER_OPTIONS $SERVER_OPTIONS_EXTRA
OPTIONS
OPTIONS_EXTRA
```

```
# -d openerp_test --db-filter=openerp_test $RUN_OPTIONS $RUN_OPTIONS_EXTRA $SERVER_OPTIONS $SERVER_OPTIONS_EXTRA
RUN_OPTIONS
RUN_OPTIONS_EXTRA
```

What do you think about it?

**Comment by jjscarafia** [comment]
@gurneyalex @lasley @moylop260 @pedrobaeza

**Comment by pedrobaeza** [comment]
I don't really get why we need extra options having the normal one...

**Comment by jjscarafia** [comment]
The idea is that, for eg, your .travis bring all the default options and then you can add your own in different builds on your runbot instance. For eg. to install other modules, languages, etc.

**Comment by moylop260** [comment]
Current environment variables to add custom params (without changes):

| MQT Steps                                   | Environment variables |
|---------------------------------------------|----------------------------------------------------|
| install dependencies (-d openerp_template)  | install_options + server_options                   |
| Run test with test-enable (-d openerp_test) | options + server_options                           |
| Alive instance (--db-filter=openerp_test)   |                                                    |

Proposal of first change

| No. | MQT Steps                                   | Environment variables |
|-----|--------------------------------|------------------------|
| 1. | install dependencies (-d openerp_template)  | install_options + server_options                   |
| 2. | Run test with test-enable (-d openerp_test) | options + server_options                           |
| 3. | Alive instance (--db-filter=openerp_test)   |   <ins> alive_options + server_options </ins> |

If you want add a extra parameter to the alive instance you could affect this environment variable.
By example: `--load-language=` or `--workers` (This parameters is not useful for step 1 and 2)

_________________

Proposal of second change
We need a extra variable to affect this parameters without overwrite them by example we are affecting [options environment from runbot_travis2docker with `docker run -e SERVER_OPTIONS="--log-db=db"`](https://github.com/OCA/runbot-addons/blob/46e399803/runbot_travis2docker/models/runbot_build.py#L120) but if a `.travis.yml` affect this variable the is overwrite, then we need a extra environment variable to set from external sources:

| No. | MQT Steps                                   | Environment variables |
|-----|--------------------------------|------------------------|
| 1. | install dependencies (-d openerp_template)  | install_options  + <ins> extra_install_options </ins> + server_options   |
| 2. | Run test with test-enable (-d openerp_test) | options  + <ins> extra_options </ins> + server_options                           |
| 3. | Alive instance (--db-filter=openerp_test)   |   alive_options + <ins> extra_alive_options </ins> + server_options |

Note: We can not concatenate current environment variable from `docker run -e VAR=value`

**Comment by nhomar** [comment]
this should be taken into account or not?

I think that have such generic values like **OPTIONS_** will be a little confusing we can open an issue per specific case @jjscarafia ?

I think what @moylop260 shared is self-explanatory or not?

feel free to re-open it if you think it this needs more discussion?

BTW with #500 refactor this kind of problems should disappear don't you think @jjscarafia
