### ISSUE TITLE
linting field names?

### ISSUE THREAD

**Issue by hbrunn** [OCA/maintainer-quality-tools#385]
In https://github.com/odoo/odoo/issues/13780, a quite difficult to find bug was introduced by the fact that some javascript code breaks if a record has a column with the name `length`.

The specific instance where this was problematic is fixed in odoo core now, but I assume a lot of community addons will have a problem with this too. As it's probably not feasible to work around the problem in every module, should we introduce a lint test that forbids some field names? In this case, it would be `length`, but I can also think of a couple of other field names I'd like to forbid, like python keywords.

**Comment by lasley** [comment]
An excellent idea 👍

**Comment by moylop260** [comment]
Thanks for report.

I didn't find the piece of js code with the problem.
Do you have a example of the code that we should avoid?

**Comment by hbrunn** [comment]
`_.each`, the rationale can be found here: http://underscorejs.org/#each

**Comment by lasley** [comment]
@moylop260 the issue is related specifically to the use of `length` as a field name. Certain views are unable to display the field due to the note linked by @hbrunn 

Here's a solid sample: https://github.com/gdgellatly/odoo_bug_demos/search?utf8=%E2%9C%93&q=length
And Here's Odoo SA doing it in one of their modules: https://github.com/odoo/odoo/blob/fc2e80cb4bcc450762c7ac5cb82a3e2d88062b38/addons/delivery/models/product_packaging.py#L12

**Comment by moylop260** [comment]
I got it
Thank you

Are there another fields name reserved for js?

**Comment by hbrunn** [comment]
I can't think of any right now. But I also couldn't think of `length` being problematic until I read this, so that doesn't say much...

**Comment by moylop260** [comment]
Fix https://github.com/OCA/pylint-odoo/pull/86

**Comment by hbrunn** [comment]
thanks!

**Comment by moylop260** [comment]
@hbrunn
Could you help us to add doc in our guidelines for this case?

**Comment by hbrunn** [comment]
I'd write something like

```
The property name `length` is used by some javascript libraries to determine if a reference points to an array or an object. As the availability of a member called `length` will break some javscript code, you shouldn't use this name at all
```

**Comment by gdgellatly** [comment]
Notwithstanding that length is already used as field name in odoo core on product model.  Years I dealt with that issue.
