### ISSUE TITLE
Tests are failing

### ISSUE THREAD

**Issue by dreispt** [OCA/maintainer-quality-tools#393]
I see tests failing due to a build timeout.
It seems to be related to the seff tests of the INSTANCE_ALIVE feature.
Might be related to #297

**Comment by moylop260** [comment]
Check my last comment https://github.com/OCA/maintainer-quality-tools/pull/390#issuecomment-263174882
Travis' team is working on this
![screen shot 2016-12-01 at 4 13 13 pm](https://cloud.githubusercontent.com/assets/6644187/20814773/b2c6d594-b7e0-11e6-9125-7bb26db66e4e.png)
