### ISSUE TITLE
ValueError: could not convert string to float: master

### ISSUE THREAD

**Issue by moylop260** [OCA/maintainer-quality-tools#398]
Steps to reproduce it:
1. Assign environment variable `VERSION="master"` in a .travis.yml
2. Wait travis build

Result:
`ValueError: could not convert string to float: master`

Expected:
Working fine like as other version of odoo/odoo

**Comment by moylop260** [comment]
The problem is the sentence [float(odoo_version)](https://github.com/OCA/maintainer-quality-tools/blame/406b428c97b35f36398c6a10d10ca57621449929/travis/test_server.py#L140) from https://github.com/OCA/maintainer-quality-tools/pull/364

@StefanRijnhart
Should we use a `script_name = 'openerp-server' if os.path.isfile('openerp-server') else 'odoo-bin'`?

**Comment by lasley** [comment]
I prefer the try/except personally. That pattern is more pythonic

**Comment by StefanRijnhart** [comment]
Fine with me!

**Comment by blaggacao** [comment]
@moylop260 `try/except` and revert #364 seems more elegant, as it reduces some method's signatures
@lasley EAFP: European Association of Fishing Pathologists, is that what you mean?? 😄

**Comment by dreispt** [comment]
@blaggacao  ["Easier to ask for forgiveness than permission."](http://stackoverflow.com/questions/11360858/what-is-the-eafp-principle-in-python#11360880)

**Comment by nhomar** [comment]
I am considering this solved, re-open it if not please.

thanks.
