### ISSUE TITLE
[Issue] createdb does not use server options (host, user, pw)

### ISSUE THREAD

**Issue by blaggacao** [OCA/maintainer-quality-tools#414]
**What is it**
the `createdb` commands are not fed the (potential) db, user and database server options, which are received by the odoo command. Instead they solely obey to standard pg env variables (`PGHOST`, `PGUSER`, `PGPASSWORD`).

**Why is it boring**
You might spend some time finding out this somewhat unintuitive behaviour.

**Why is it (almost) blocking (in some cases)**
In some CIs (eg gitlab-ci) you can define the used database as "service", internally it just downloads a docker images and binds it to the runner container under it's name. So if you define service `postgres` it will be available under the hostname `postgres` to your services. Because of the above said, you then define unsuspectingly `PGHOST=postgres`. Results, that the whole environment is shared to postgres image, so it's run command and init script will fail, as it is supposed to run against `localhost`, not `postgres`. 

**Rationale**
The argument here is that in a given environment the main consumer of `PG*` variables should be postgres itself, MQT should not conflictingly consume those variables, but rather stick with the more scoped ones contained in `SERVER_OPTIONS`. This is a typical design problem of the config by environment variable pattern. I suggest preparing a fix which makes MQT give precedence to `SERVER_OPTIONS` over `PG*` variables, if set. 

@moylop260  would you accept such PR?

**I can guess the questions...**
- Yes, it can be worked around by sub shelling `(export PGHOST=postgres; export PGUSER=Testuser; export PGPASSWORD=Testpassword; travis_run_tests)`
- No, although a necessary solution, this is not sufficient, as we do not want to twist people's minds for no particular reason, except for own comfort. We should be nice with the user, shouldn't we?

**Comment by moylop260** [comment]
+1 to send `os.environ` to `popen` methods

**Comment by nhomar** [comment]
I think this was solved on #413 if not please re-open it.
