### ISSUE TITLE
[Idea] - "run_server.py" Sounds dangerous? Naah!

### ISSUE THREAD

**Issue by blaggacao** [OCA/maintainer-quality-tools#417]
**What is it**
A sister package to `test_server`, called `run_server` which becomes the preferred way of launching an odoo server, by features like automatic db templating similar to what `test_server` does for testing.

**Why is it**
It's just nice to have and fun to have.

**What would be especially nice**
- Automatic DB templating (based on the repos dependencies) at startup
- Automatic db filter based on the repo slug, so everything else get's out of the way
- A colourful heads up at the beginning of the logs at startup (with OCA branding, of course 😄)
  - This can be abused in a positive way.
  - Like URL's to coding guidelines, api docs, whatever
- Opinionated, but [WDB](https://github.com/Kozea/wdb) is just an extremely appealing debugging default for average odoo programmers. Batteries included, but removable.
- Smart default loghandler(s!). Batteries included, but removable.
- Optionally setting things up for example git clones of oca-dependencies. Just like `test_server`. Batteries included, but removable.

**Questions...**
- Which wheel am I reinventing? Something scoped that takes over, where the odoo world gets non compliant to standard procedures would be ok, I guess.
- Yes, it potentially makes a great candidate for docker entrypoint scripts.
- Yes, this is brain cinema only so far. Relax and enjoy!

**Comment by dreispt** [comment]
Regarding this, what we want is to have MQT able to run as a command line tool.
I have started work on this. 
The challenge is to do that keeping changesets small and very readable, since MQT is a quite sensitive tool.
Probably the best approach is the one you mention: add a script to be used in the command line, taking care to set all the env variables the current code expects to find.

**Comment by blaggacao** [comment]
Nice, so I'll have you opinion before I might start working on something these days. We use a init script in bash which does the job, but having this inline with MQT would be a bliss...

There is one thing to analyze: Docker is a really powerfull and cross platform tool for managing dev environments seamlessly, but on the other hand, probably we are not ready for such an opinionated move. If we would be constructing some `docker-compose` which sets up everything (db, wdb, odoo, code) would be the ultimate killer...

But on a first move, a `run_server` that is not built with only the traditional virtualenv setup in mind would be great...

**Comment by dreispt** [comment]
For me, MQT should become a pip-installable CLI tool.
It should be irrelevant if it is then used on Docker, TravisCI or whatever.

**Comment by blaggacao** [comment]
I'm working on setup for automated migrations testing with following staging instances (as a runbot replacement) so I stumbled over the `instance_alive` directive. What it does?

1. [Here](https://github.com/OCA/maintainer-quality-tools/blob/master/travis/test_server.py#L378), it start's a normal erp instance, if the test_database already exists. This is kind of a stump of the idea discussed herein.
2. [Here](https://github.com/OCA/maintainer-quality-tools/blob/master/travis/test_server.py#L418), it refuses to drop the testing database, if set.

At least the first point goes into the same direction and for the sake of good design, I think (if I'm not missing any use case), it should be taken out of `test_server` and `run_server` made entirely responsible for running a server. The fact that with (1.) it refuses to override test_database if set, we would need extra unnecessary glue code to handle database renaming/deletion and assure a maintenance free flow.
@moylop260 What was your though when you commited in https://github.com/OCA/maintainer-quality-tools/commit/600700de725c1d2752a80925d8ca14fec6a1a665? I mean, explicitly, (2.) is fine. (1.) could be rather handled by the object of this discussion?

**Comment by blaggacao** [comment]
Reading through other issues:

**Curated Sublime Text Snippets**
Well sublime is opinionated, but widely used, there can be other editors provided, but the work on sublime is already pretty advanced https://github.com/sotogarcia/sublime-odoo-snippets (and forks!)

**Pre-Commits and Editor Linting**
Provide for instructions to do pre-commit checks and editor linting integration. The latter is probably the most effective and strategic measure towards quality assurance through preemptive and very closed circuit feedback loops.

**Comment by nhomar** [comment]
I will considere this comments and information after the refactor on #500 if everybody thinks it is feasible to do on this repository.

Closing as an Idea.
