### ISSUE TITLE
[Opinion] - Batteries included, but removable

### ISSUE THREAD

**Issue by blaggacao** [OCA/maintainer-quality-tools#418]
**What is it**
Being installing the packaged debian the default version of deploying odoo, testing it with travis on a usual open sourced repository, there are some strange folks in middle earth that like a little more control. Custom forks, without the overhead of packaging. Custom builds of some dependencies. Prebacked runner images for different CIs (eg drone.io or gitlab-ci). You name it...

**Why is it**
It will be nice, if thanks to further discussions, `travis` would be re-perceived as batteries included, but removable. Seeing the potential of MQT, it would be a pity, if in the further development of MQT, the broader use case would be under-appreciated. And if it's agnosticity would suffer, remember: `agnostic == strategic; True`

**So, what is this about**
A plea for acknowledging the other use case. Just that, as a food of thought.

**Comment by nhomar** [comment]
wip here:

#500
