### ISSUE TITLE
More conformity checks

### ISSUE THREAD

**Issue by bwrsandman** [OCA/maintainer-quality-tools#42]
Using the flake8 test, we could do more checks such as:

- [x] is there a LICENSE file
- [x] pylint score
- [x] ~~xmllint score~~
- [ ] jshint (javascript linter, in package `node`)
- [x] ~~dtd verification of data and view xmls~~
- [x] are there `#vim` lines.
- [x] is encoding specified
- [x] only valid `__openerp__.py` keys used
     - [ ] [Odoo conventions](https://github.com/nbessi/openerp-conventions)
     - [ ] See if @nbessi is ok with us adopting openerp-conventions
- [x] Is deprecated python used (e.g. `except Exception, e`) W0703 
- [x] performance analysis
- [x] Are there any warnings (deprecated things, missing permissions)
- [ ] Check if button object functions return dicts/ir.actions 
- [x] ~~Presence of `i18n/module_name.pot`~~
- [x] OCA is in the Author of Module
- [x] multiple author are in correct csv format in Module
- [ ] Module description is as README.rst with OCA template
- [x] [pep8-naming](https://github.com/flintwork/pep8-naming)

**Comment by gurneyalex** [comment]
@bwrsandman I would welcome a check for the presence of a `i18n/module_name.pot` file

**Comment by bwrsandman** [comment]
@gurneyalex Thanks, added.

**Comment by bwrsandman** [comment]
Checked `Presence of i18n/module_name.pot` due to transifex doing that export itself

**Comment by moylop260** [comment]
Hello,
Many checks of this issue are fixed here:
https://github.com/OCA/maintainer-quality-tools/pull/234

You feedback is welcome.

**Comment by moylop260** [comment]
Now, many of this issue is fixed.
I created a new one to manage new ideas of checks with pylint-plugin
https://github.com/OCA/maintainer-quality-tools/issues/252
