### ISSUE TITLE
[Architecture] Organiation on MQT

### ISSUE THREAD

**Issue by blaggacao** [OCA/maintainer-quality-tools#422]
**What is it**

- It's so confusing... I can't easily perceive the design and architecture of the linting part of MQT.
- It's not usable on Windows (breaks).
- It's hard to carve things out of the travis use case, especially in sight of #417 

**What specifically**

- `run_pylint` is a cli tool, greate! ~~(I'll refactor it to http://docopt.org/ to set the standard)~~
- `test_flake8` and `test_pylint` should be cli as well with a similar api.
- any of those cli can then double up as `pre-commit`, see http://omerkatz.com/blog/2013/5/23/git-hooks-part-2-implementing-git-hooks-using-python
- Therefore ugly bash-only `pre-commit` can be deprecated in the mid term (bash is not even on every unix I know and less so on windows).

**What's possibly next**

- ~~Refactor `run_pylint` to docopt~~ I know now, why click was chosen (http://click.pocoo.org/5/why/#why-not-docopt-etc)
* [x] Replace custom git command by a readily available git interface, so git operations can be eventually abstracted without reinventing the wheel and keeping codebase smaller here. (cleared in #423)
* [x] Factor out run_pylint, test_flake8 and test_pylint into a well designed `cli` folder, which could then grow into a `mqt` command in sight of #417 (#424 is on it)

**Comment by nhomar** [comment]
WIp here:

#500 

comments will be taken into considerations.
