### ISSUE TITLE
[RFC] PhantomJS Features Output

### ISSUE THREAD

**Issue by lasley** [OCA/maintainer-quality-tools#438]
From https://github.com/OCA/maintainer-quality-tools/pull/437#pullrequestreview-28043707 - I figured it was best to break it out here:

------

I wish we could have some [features.js](https://github.com/ariya/phantomjs/blob/master/examples/features.js) output somewhere to know what features are supported in PhantomJS, because that list + caniuse.com would be the reference to know what ES2015+ features we could start using (and I'm eager for many of them! 🙏 ).

------

I think this is a good idea, and will implement it. It's unfortunately not as simple as just calling the script, so I am making an issue instead of expanding scope of the existing PR.

```
odoo@odoo-dev-10:~$ node  /usr/local/lib/node_modules/phantomjs-prebuilt/lib/phantom/examples/features.js 
/usr/local/lib/node_modules/phantomjs-prebuilt/lib/phantom/examples/features.js:4
phantom.injectJs('modernizr.js');
^

ReferenceError: phantom is not defined
    at Object.<anonymous> (/usr/local/lib/node_modules/phantomjs-prebuilt/lib/phantom/examples/features.js:4:1)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
```

**Comment by lasley** [comment]
cc @Yajo

**Comment by Yajo** [comment]
Most likely you will have to [run the script with `phantomjs`](https://github.com/odoo/odoo/blob/ab9852331589ac344d9d8143ff402be0b9d4c601/odoo/tests/common.py#L434) instead of `node`.

BTW once you do that, I guess it will fail if modernizr is not in its path.

**Comment by lasley** [comment]
Derp I dunno why I didn't think of that! Works great!

I'll implement this once #437 is merged in order to avoid conflict.

```
odoo@odoo-dev-10:~$ phantomjs /usr/local/lib/node_modules/phantomjs-prebuilt/lib/phantom/examples/features.js 
Detected features (using Modernizr 2.8.2):

Supported:
  flexbox
  flexboxlegacy
  canvas
  canvastext
  touch
  postmessage
  websqldatabase
  indexeddb
  hashchange
  history
  draganddrop
  websockets
  rgba
  hsla
  multiplebgs
  backgroundsize
  borderimage
  borderradius
  boxshadow
  textshadow
  opacity
  cssanimations
  csscolumns
  cssgradients
  cssreflections
  csstransforms
  csstransforms3d
  csstransitions
  fontface
  generatedcontent
  localstorage
  sessionstorage
  webworkers
  applicationcache
  svg
  inlinesvg
  smil
  svgclippaths

Not supported:
  webgl
  geolocation
  video
  audio
```

**Comment by Yajo** [comment]
Interesting 🤔 

I thought this would dump some data about supported syntax, such as arrow functions, async-await, asm, webassembly, class, let, etc.

ATM syntax errors are the most critical part of upgrading the JS, given Odoo minifies and concatenates everything, which means that a syntax error breaks *all* JS in a page.

**Comment by lasley** [comment]
Agreed, this gets me too.

I wonder if it's possible to run Odoo tests under `?debug=assets` without actually placing that in the test URIs in all of the Python files.

**Comment by Yajo** [comment]
I think you'll have to put it. We should add it [in the template](https://github.com/OCA/maintainer-tools/blob/master/template/module/tests/test_something.py#L31).

**Comment by lasley** [comment]
I almost want to instead just add an HTTP case in our OCA lib that does this for us implicitly. But yeah, your way is better probably 😆 - #265

**Comment by pedrobaeza** [comment]
PhantomJS is deprecated in v12 and this contributor is no longer active, so I close.
