### ISSUE TITLE
Missing OCA in authors should be a blocking error

### ISSUE THREAD

**Issue by sbidoul** [OCA/maintainer-quality-tools#443]
In [this PR](https://github.com/OCA/l10n-thailand/pull/3#discussion_r114944050), we were surprised that travis was green while OCA was not in the manifest author key.

I propose this becomes a blocking error in MQT.

It is easy to do as it only requires changing a [configuration file](https://github.com/OCA/maintainer-quality-tools/tree/master/travis/cfg).

The drawback is that people using the MQT repo outside OCA would get an error. Such people can use their own pylint-odoo configuration files, tuned for their own projects outside of OCA, so IMO we should make this check a blocking error in OCA.

What do you think?

**Comment by bealdav** [comment]
:+1:
