### ISSUE TITLE
Broken travis on partner-contact@10.0: Modules loaded message not found

### ISSUE THREAD

**Issue by Yajo** [OCA/maintainer-quality-tools#448]
Hi there, [Travis is broken in branch 10.0 of partner-contact](https://travis-ci.org/OCA/partner-contact/builds/238182014). All PR for that branch are going ❌:

![captura de pantalla de 2017-06-01 13-22-34](https://cloud.githubusercontent.com/assets/973709/26677718/6cb5769c-46cd-11e7-90f4-4dc93f73f3b2.png)

@pedrobaeza Tried to fix it with https://github.com/OCA/maintainer-quality-tools/commit/be28ef3ec0cb13c96b50b0a639f1bc316c64120c but seems like it is still broken.

It appears to me like it aborts the unit testing due to some kind of timeout and [this seems to be the relevant error message: `Modules loaded message not found.`](https://travis-ci.org/OCA/partner-contact/jobs/238182017#L1085) But honestly I have no idea. Could anybody check that please?

@Tecnativa @moylop260 @lasley

**Comment by dreispt** [comment]
> Tried to fix it with be28ef3 but seems like it is still broken.

Was that a direct commit without a PR a peer review?

**Comment by dreispt** [comment]
Could it be failing because the "error" string is [found in the log](https://travis-ci.org/OCA/partner-contact/jobs/238182017#L1047)?
If so, it is still strange, because https://github.com/OCA/maintainer-quality-tools/issues/447 reports the opposite problem.

I suggest you to try changing the tests messages remoiving the "error" text string from them.

**Comment by moylop260** [comment]
The log there is not the special log output `openerp_test odoo.modules.loading: Modules loaded.`
I'll review the reason becuase odoo don't emit this message.

FYI the runbot log show this output fine:
https://runbot2.odoo-community.org/runbot/static/build/3293653-10-0-1bc94d/logs/job_20_test_all.txt

My first hypothesis is: A rare test failing of a rare way

**Comment by Yajo** [comment]
But if it were rare, partner-contact would be going ✔️ sometimes, but that branch is fully red, no?

**Comment by moylop260** [comment]
I have created a t2d and I saw that the last tests from: partner_identification/tests/test_res_partner.py was freeze.

Too much time and don't continue...
I think that here there is a problem with the cursor and blocked records from database.

**Comment by lasley** [comment]
This started with OCA/partner-contact#419, specifically when tests were introduced for the search feature. I think the culprit is [this](https://github.com/OCA/partner-contact/pull/419/files#diff-57c0be4b932b0c2f4c5898b79b4a26acR120)

**Comment by moylop260** [comment]
Yeah that is the reason.
FYI I detected a infinite loop using that [search](https://github.com/OCA/partner-contact/blob/1bc94dff59c405c4ac6c3eecb6ff2499accfacb1/partner_identification/tests/test_res_partner.py#L123) parsing the domain:
[odoo/osv/expression.py#L781](https://github.com/odoo/odoo/blob/79477b8d96be47cca5609ce5e4dd84a7e7f64f0a/odoo/osv/expression.py#L781)

**Comment by dreispt** [comment]
@moylop Do you think it's a bug in the ORM? The loop contains a pop() that will inevitably exhaust the collection.

**Comment by moylop260** [comment]
FYI `category_id.code='SSN'` increase for each iteration of the loop:

![screen shot 2017-06-01 at 12 11 13](https://cloud.githubusercontent.com/assets/6644187/26691178/cececcc2-46c1-11e7-9807-fe7f2b3cdc47.png)


This is not a MQT issue
Should we close it and create other one from the project with the problem.

**Comment by moylop260** [comment]
I don't know if there is a issue with the ORM but the infinite loop looks a problem with this fields:

https://github.com/LasLabs/partner-contact/blob/b41812f3a78c6630ea3d957012883fe70feaa686/partner_identification/tests/test_res_partner.py#L13-L23

**Comment by moylop260** [comment]
I close this issue because is not a MQT one.

I have created the following issue related with the real project:
https://github.com/OCA/partner-contact/issues/434
