### ISSUE TITLE
[TRAVIS] Can't install apt package python-lxml

### ISSUE THREAD

**Issue by moylop260** [OCA/maintainer-quality-tools#467]
Travis in the process:
`Installing APT Packages (BETA)` show the error:
 - `W: --force-yes is deprecated, use one of the options starting with --allow instead.`

e.g. https://travis-ci.org/OCA/website/jobs/255555596#L460

The error was reported https://github.com/travis-ci/travis-ci/issues/8132

I have 2 solutions:
1) Wait a travis fix
2) Run from MQT `pip install lxml`

**Comment by pedrobaeza** [comment]
What a busy weeks we have with Travis lately... Let's wait if they tell us something.

**Comment by Yajo** [comment]
Couldn't we just use a docker image that has everything inside? Besides fixing this kind of 💩, CI would be much faster (no need to install every single time every single dependency).

**Comment by sbidoul** [comment]
If people are interested, I'm maintaining [manylinux](https://www.python.org/dev/peps/pep-0513/) wheels for all odoo and most OCA dependencies.

So pip install -f https://wheelhouse.acsone.eu/manylinux1 requirements.txt installs everything very fast, without the need for a C compiler nor any additional dependency except python 2.7 and virtualenv.

**Comment by moylop260** [comment]
Runbot uses a custom image with all pre-installed.
But travis don't allow to choose a custom image.

Instead travis use pip cache feature maybe we should use lxml from requirements.txt and cached it...

**Comment by Yajo** [comment]
Why travis does not allow that? All you have to do is add the docker service and then execute the corresponding commands... 😕

**Comment by lasley** [comment]
@Yajo - Travis will allow it in that instance, but you would be running in their sudo (non-containerized) infrastructure

**Comment by moylop260** [comment]
Oh! I got it
You  are talking about use `sudo: true, service: docker` configuration.
mmm... We don't have MQT ready to do that but maybe using t2d could be faster implementation.

The architecture is funny "Using a `dockerized travis` to use `travis to docker`"

We need work in a light docker image with all current advantages used from current official travis one to faster builds because the docker image is not cached 😢  (runbot cache docker image)

The tests to work with this new light image is: `travis2docker --docker-image={NEW_IMAGE} {PROJECT} {BRANCH}` and run the script if all is fine we can follow this line.

The question is Who start this hardly work?

**Comment by pedrobaeza** [comment]
There's no answer from Travis, so we need to get rid of this. @moylop260, can you please make the change for installing lxml from pip or the solution told by @sbidoul ?

**Comment by moylop260** [comment]
FYI https://github.com/OCA/maintainer-quality-tools/pull/470
