### ISSUE TITLE
Sass not installing correctly

### ISSUE THREAD

**Issue by Yajo** [OCA/maintainer-quality-tools#471]
Hi there! @moylop260 @lasley 

I just broke branches [9](https://travis-ci.org/OCA/e-commerce/builds/257626079) and [10](https://travis-ci.org/OCA/e-commerce/builds/257617354) of e-commerce by adding a direct commit that added the `WEBSITE_REPO="1"` shortcut from #465.

Yeah, maybe I should have opened PRs, but it seemed like that simple line would fix many of them by just rebasing. It turns out it broke everything 😭 

The main problem seems to be that [you cannot use `rvm use ruby --latest` in travis due to some permissions problem](https://travis-ci.org/OCA/e-commerce/jobs/257617357#L353-L354). That [makes `bootstrap-sass` not to install](https://travis-ci.org/OCA/e-commerce/jobs/257617357#L361-L362), and aborts the whole build.

I could rollback the commits, but I'm not sure if it's the best option. We need Sass, any ideas on fixing that?

**Comment by pedrobaeza** [comment]
For the moment just revert the commits.

**Comment by Yajo** [comment]
All reverted.

**Comment by lasley** [comment]
Hmmmm I think there is something more here - this is working fine in [website](https://github.com/OCA/website/blob/10.0/.travis.yml#L18) per [10.0 build](https://travis-ci.org/OCA/website/jobs/257695642)

**Comment by Yajo** [comment]
Can anybody reopen? This is not fixed yet.

**Comment by moylop260** [comment]
@Yajo 
I'm a little lost here.
Could you help me to upgrade me for this issue?

What are the steps to reproduce the error in the log of the travis and what is the steps to review if runbot was installed fine?

**Comment by moylop260** [comment]
Or Can you create a dummy PR for a project where runbot and travis are failing?

Because I saw the configuration `WEBSITE_REPO="1"` from
https://github.com/OCA/e-commerce/blob/10.0/.travis.yml#L30

With green results:

 - ![screen shot 2017-08-11 at 11 28 40](https://user-images.githubusercontent.com/6644187/29221916-2030cf56-7e86-11e7-9114-aa8dfb43c7e8.png)

**Comment by pedrobaeza** [comment]
The problems are in 9.0 branch: https://github.com/OCA/website/tree/9.0

**Comment by lasley** [comment]
@moylop260 - Dude I'm lost too, this issue's stupid. In e-commerce it's only replicating on [v9. Feel free to play with this PR](https://github.com/OCA/e-commerce/pull/195).

But then in website, it's a [v10 issue too](https://github.com/OCA/website/pull/365).

**Comment by pedrobaeza** [comment]
The problem is seen also trying to access a runbot instance, so it can be something with t2d.

**Comment by moylop260** [comment]
> The problem is seen also trying to access a runbot instance, so it can be something with t2d.

So this issue talk about runbot using t2d for 9.0 branches?

But travis is working properly? (Because travis is not using t2d)

**Comment by lasley** [comment]
Are you sure this is also apparent on Runbot, Pedro? IIRC the PR that was mentioned in ended up being solved with a fix commit. I can't find it now though...

**Comment by lasley** [comment]
We have been ping ponging between Runbot and Travis fails though. Pretty sure Runbot is solved

**Comment by pedrobaeza** [comment]
No, the problem is to find a combination that success in both Runbot and Travis. If Travis works, runbot doesn't. If runbot runs, then Travis goes away. The pity is that my colleague goes today to holidays, so we won't get exact links in 1 week.

**Comment by pedrobaeza** [comment]
I will review the PRs then to see exactly.

**Comment by lasley** [comment]
Damn so that's why I've noticed the ping ponging. I didn't realize it was a consistent red vs green

**Comment by moylop260** [comment]
@lasley The pr https://github.com/OCA/e-commerce/pull/195 have the flags enabled but have `before_script` too man
Is this correct?

**Comment by lasley** [comment]
Ummmmm it's definitely not - I could have sworn I deleted that, but I guess I just did too many at once & got sloppy. Removed.

Seriously if that was it I'm going to the bar early this morning.

**Comment by moylop260** [comment]
Could you use my dev branch?
 - https://github.com/OCA/maintainer-quality-tools/pull/478

**Comment by moylop260** [comment]
The main issue was that the `before_install` never was deleted in the .travis.yml of the project related.
So the sass versions installed are wrong because:
 - https://github.com/OCA/maintainer-quality-tools/pull/465#issuecomment-316308930

 - before_install: Install wrong version
 - MQT: Can't fix the wrong version

You can fix it with 2 options:
1. Remove before_install
2. MQT can fix wrong versions

This PR fix the second option if you forgot it something.

So we can merge it
