### ISSUE TITLE
Disable one pylint check in the build

### ISSUE THREAD

**Issue by danimaribeiro** [OCA/maintainer-quality-tools#480]
Is it possible to disable one pylint check in my repository with some config file?

Especifically I want to disable this check:
manifest-required-author

**Comment by lasley** [comment]
I haven't tried it with the `manifest-required-author` specifically, but you can disable by line like this:

```
a_line  # pylint: disable=C1234
```

**Comment by danimaribeiro** [comment]
It works, thanks.
