### ISSUE TITLE
[RFC] Freeze Requirements Files

### ISSUE THREAD

**Issue by lasley** [OCA/maintainer-quality-tools#494]
We recently came up with an [issue in server-tools](https://github.com/OCA/server-tools/issues/1011#issuecomment-334509928) where the API was changed in a library, which caused a test that was previously passing to fail. This is an interesting case that can happen in basically all of our repos now that I'm looking at it - we've all been slacking on freezing the requirements versions.

I think part of the reason we slack at this is that (at least IMO), freezing requirements should be a part of the build pipeline and not something that is left to a developer. I think my standpoint might be at odds with the general community though, but my counter is that a developer can also stick the version manually if they so choose.

The requirements of this would be fairly simple, especially now that we start with clean branches. Basically if the `requirements.txt` file is edited in a PR, the PR is merged, and the CI goes green on  the branch, we need to freeze the version of anything that doesn't already have a frozen version.

Does anyone have some thoughts on this, both in terms of general theory as well as how to accomplish it? I think maybe the script that updates the `ReadMe.md` would be the good place to inject this?

cc @sylvain-garancher @moylop260

**Comment by sylvain-garancher** [comment]
I agree, it would be fine to have at least a guideline about that.
But I'm not in favor of an automatic definition of fixed versions.

cc @gurneyalex @pedrobaeza

**Comment by sbidoul** [comment]
@lasley Here is [an article](https://caremad.io/posts/2013/07/setup-vs-requirement/) by one of the best experts on the topic of python dependency management.

Using the terminology of that article, Odoo addons are more akin to libraries than applications. Therefore addons should state a minimum supported version if needed (eg `oauthlib>=2`), but not freeze an exact version.

IMO it's a good think that tests break when an dependent API changes. It show great test coverage.

Freezing must occur when a downstream integrator delivers to its customer, not in OCA repos.

**Comment by lasley** [comment]
Thanks for the elaboration (and great read) @sbidoul. Alright I'm convinced, automatic is bad.

**Comment by pedrobaeza** [comment]
I don't think we should freeze requirements, and in addition to the current comments, I have to add that making that we will find conflicts between versions on dependencies.

**Comment by dreispt** [comment]
Security-wise shouldn't we try to use the latest version possible?

**Comment by hbto** [comment]
It is recommended to keep the requirements frozen as per @pedrobaeza suggestion.

That has some pro's & con's as we know,

One of the pro's: we keep our libraries up-to-date with security fixes, if any,

One of the con's: we do not suffer from the symdrome `... But it works on my machine`

Having that in mind, people using stable versions shall keep using frozen versions of the libraries.
People making R&D can afford to use the cutting edge version of the libraries and point us out what could be fine or wrong with it.

Regards.
