### ISSUE TITLE
Transifex not working for v11

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/maintainer-quality-tools#495]
txclib is not compatible with Python 3. As we are migrating to Weblate, I propose to directly remove the step of travis.yml files.

cc @max3903 @moylop260 @gurneyalex

**Comment by moylop260** [comment]
+1

**Comment by dreispt** [comment]
+1

**Comment by pedrobaeza** [comment]
Fixed in https://github.com/OCA/maintainer-quality-tools/commit/27792ba2e1e95212c1a0670784bdd3cd1a5b33c0

Example of correct build: https://travis-ci.org/OCA/reporting-engine/builds/289522069
