### ISSUE TITLE
Checks to disable in JS

### ISSUE THREAD

**Issue by Yajo** [OCA/maintainer-quality-tools#498]
These lints should be disabled IMHO:

- `[W7903(javascript-lint), ] Use the rest parameters instead of 'arguments'. [Error/prefer-rest-params]`: If we obey this, PhantomJS will die silently there.
- `[W7903(javascript-lint), ] Unexpected trailing comma. [Error/comma-dangle]`: It seems the only browser that fails with this is IE<=8, which I don't give a _ship_ for.

See them live at https://travis-ci.org/OCA/web/jobs/291496379#L734-L741

**Comment by moylop260** [comment]
@oscarolar @hugho-ad What do you think about?

**Comment by oscarolar** [comment]
+1 for the first one and -1 for the second one, there are still IE8 users out there.

**Comment by oscarolar** [comment]
ok, +1 for both, nevermind IE8 https://www.netmarketshare.com/browser-market-share.aspx?qprid=2&qpcustomd=0

**Comment by hugho-ad** [comment]
+1

**Comment by lmignon** [comment]
:+1:

**Comment by moylop260** [comment]
FYI https://github.com/OCA/pylint-odoo/pull/167
