### ISSUE TITLE
Travis red: Make travis green again.

### ISSUE THREAD

**Issue by nhomar** [OCA/maintainer-quality-tools#505]
@moylop260 

Just to have it in the radar:

Can you explain what nee to be merged to have this green again and avoid merge red stuff?: 

![image](https://user-images.githubusercontent.com/338634/32194742-d834844c-bd80-11e7-9748-ee0acc720369.png)

**Comment by pedrobaeza** [comment]
#504 addresses what he told me, but it's also red.

**Comment by moylop260** [comment]
FYI reverting the direct commit https://github.com/OCA/maintainer-quality-tools/commit/27792ba2e1e95212c1a0670784bdd3cd1a5b33c0 now is green again.

 - https://github.com/OCA/maintainer-quality-tools/pull/506

**Comment by pedrobaeza** [comment]
Uhm, I don't get it, #504 fixes the "not at the top level import". I'm not able to identify other issue. Can you help me?

**Comment by moylop260** [comment]
Yes of course.

Running `flake8 travis` command in your PR the result was:

```bash
travis/odoo_connection.py:78:9: F401 'odoo.modules.registry.Registry' imported but unused
travis/odoo_connection.py:87:20: F821 undefined name 'RegistryManager'
```

Checking the code you have `from odoo.modules.registry import Registry` but is not used. In fact, you are using `RegistryManager.new(self.dbname)`.

The message output of travis build result is not so clear neither but you can see the result here:
 - https://travis-ci.org/OCA/maintainer-quality-tools/jobs/294735026#L884

I hope it helps

**Comment by pedrobaeza** [comment]
Now it's green! Please check #504 and merge for cleaning the branch

**Comment by moylop260** [comment]
Fixed from https://github.com/OCA/maintainer-quality-tools/pull/504
