### ISSUE TITLE
Tests can leave residue, causing other tests to fail

### ISSUE THREAD

**Issue by lasley** [OCA/maintainer-quality-tools#511]
This is another issue that we've been struggling with for a while, most notably in `server-tools` where we now have [three sets of builds in the matrix](https://github.com/OCA/server-tools/blob/10.0/.travis.yml#L24). 

The bad part about this, aside from the lack of Runbot testing on the edge branches, is that I am almost positive the issue is not being caused by `database_cleanup` or `auth_session_timeout` & the suspect module is still in the repo to cause more issues.

I spent a solid few hours debugging this when it happened with `database-cleanup` in order to find a module combination that would cause the issue. As it stands right now, it's impossible and must be done with isolated matrices in a hunt and peck manor.

The only solution I can think of here is to isolate every single test into its own database, then have another database that includes an installation of all of the modules - but without actually running their tests.

Huge con to the above is that it will increase our build time exponentially. I'm wondering if someone has a better idea though

**Comment by lasley** [comment]
cc @moylop260

**Comment by lasley** [comment]
And as if an omen, a PR was just reviewed that contains a live example https://github.com/OCA/server-tools/pull/995

**Comment by moylop260** [comment]
FYI using UNIT_TESTS="1" parameter you will have 1 database for each module.

NOTE: We have too much without use this feature, maybe is broken... but I understand that is your request... right?

**Comment by pedrobaeza** [comment]
Closing as no answer.
