### ISSUE TITLE
[11.0] test_pylint is considering error C8201(no-utf8-coding-comment), ]

### ISSUE THREAD

**Issue by jbeficent** [OCA/maintainer-quality-tools#514]
In https://github.com/OCA/account-financial-reporting Travis is raising, for a PR to v11, an error of missing utf-8 in headers here:https://travis-ci.org/OCA/account-financial-reporting/jobs/307880124 an error C8201(no-utf8-coding-comment), ]

These errors should be ignored in 11.0 with python 3

**Comment by moylop260** [comment]
FYI duplicated issue from https://github.com/OCA/pylint-odoo/issues/164
