### ISSUE TITLE
Codecov: No report found to compare against

### ISSUE THREAD

**Issue by StefanRijnhart** [OCA/maintainer-quality-tools#515]
I proudly fixed the tests of server-tools/8.0, but codecov makes me look bad.

https://github.com/OCA/server-tools/pull/1075

![image](https://user-images.githubusercontent.com/1033124/33402508-0f7e5006-d55d-11e7-9910-288213d1ebfd.png)

Clicking on either `details` link gives this result:

![image](https://user-images.githubusercontent.com/1033124/33402520-1dd70f58-d55d-11e7-9924-db2e945162ea.png)

**Comment by moylop260** [comment]
Could be the same case from https://github.com/codecov/codecov-python/issues/120?

**Comment by pedrobaeza** [comment]
In this case it's because as we haven't never got a correct build, there has never been a coverage report. When the PR is merged, you'll have the first coverage report and the rest of the PRs will count with a proper coverage comparison.

**Comment by StefanRijnhart** [comment]
Tests are only broken since two weeks or so.

**Comment by pedrobaeza** [comment]
But maybe codecov doesn't save old results... The same error is happening in 11.0 branches till the first PR is merged.

**Comment by StefanRijnhart** [comment]
Can we make codecov not fail tests if this is the case? It is quite disheartening: spend effort just to fix tests and get a red cross in return.

**Comment by StefanRijnhart** [comment]
![image](https://user-images.githubusercontent.com/1033124/33403404-95420d42-d560-11e7-9a87-1992d3d51d4b.png)

**Comment by StefanRijnhart** [comment]
From https://github.com/codecov/support/issues/173#issuecomment-216067683:
```
coverage:
  status:
    project: 
      default:
        target: auto  # this is default
        if_not_found: success  # no commit found? still set a success
```

**Comment by pedrobaeza** [comment]
Let me try to put that in the global configuration and restart Travis to see.

**Comment by pedrobaeza** [comment]
OK, now we have the project part correct, but it still lacks the patch one:

![seleccion_026](https://user-images.githubusercontent.com/7165771/33404666-7412f2b2-d565-11e7-8410-e22af38c321f.png)

I'm going to figure out the same structure for patch YAML line to see if it works also.

**Comment by pedrobaeza** [comment]
I have followed the syntax on https://codecov.readme.io/v4.3.6/docs/commit-status#section-patch-status. Maybe it should apply only for new PRs made from now on?

**Comment by StefanRijnhart** [comment]
Let me close this one and reopen

**Comment by StefanRijnhart** [comment]
Doh I closed the issue instead of the PR...

**Comment by StefanRijnhart** [comment]
It worked! Thank you so much!

![image](https://user-images.githubusercontent.com/1033124/33421571-c3508acc-d5b2-11e7-8cd8-b191389f7720.png)
