### ISSUE TITLE
How to start up with the Maintainer-Quality-tools With Odoo custom addons

### ISSUE THREAD

**Issue by cdasadiya74** [OCA/maintainer-quality-tools#517]
Hi,

Any One help me how I can setup with maintainer-quality-tools with my custom addons?
For the installation purpose.
Any documentation available for that ?
Guide me the differentiate between [maintainer-tools](https://github.com/OCA/maintainer-tools) & [maintainer-quality-tools](https://github.com/OCA/maintainer-quality-tools)

**Comment by pedrobaeza** [comment]
If you want to set a check for guidelines, see https://github.com/OCA/maintainer-quality-tools/blob/master/git/README.md. If you want to set a CI engine like Travis, that's something not easy and it can't be explained here.

**Comment by cdasadiya74** [comment]
@pedrobaeza thanks for your reply. if you know any things more or have some stuff regarding my query then do share with me on c.dasadiya74@gmail.com

**Comment by pedrobaeza** [comment]
No if you don't give more details of what do you want to achieve.

**Comment by cdasadiya74** [comment]
ok

**Comment by cdasadiya74** [comment]
ok thank you

**Comment by yelizariev** [comment]
You need to add ``.travis.yml`` files to your custom repository and probably update your fork of maintainer-quality-tools.

Check my fork as an example: https://github.com/it-projects-llc/maintainer-quality-tools
And my custom travis file: https://github.com/it-projects-llc/misc-addons/blob/11.0/.travis.yml
For custom runbot this may help: https://github.com/it-projects-llc/odoo-runbot-docker

**Comment by lasley** [comment]
I typically just cut out the fork of MQT and use the OCA one directly - https://github.com/LasLabs/vertical-medical/blob/release/10.0/.travis.yml

I'm curious - What are you doing differently in the fork @yelizariev?

**Comment by yelizariev** [comment]
It's  [configs](https://github.com/it-projects-llc/maintainer-quality-tools/tree/master/travis/cfg), [forcing to use our fork of pylint-odoo](https://github.com/it-projects-llc/maintainer-quality-tools/commit/a327cec81ef4690109e9b3c0c8d0c516f964d461), updates for [transifex](https://github.com/it-projects-llc/maintainer-quality-tools/blob/master/travis/travis_run_tests) and [using our OCA forks by default](https://github.com/it-projects-llc/maintainer-quality-tools/commit/430439ee84ef8bee7f40cad27ffcfbf67350ffe1) (It's needed when PR to OCA is not merged, but we willing make other module in our repository, which depends on that PR -- we merge it to our forks and carry on)

**Comment by lasley** [comment]
Thanks for the elaboration, @yelizariev - I'm going to dig into these and possibly implement on my end. I know pylint specifically gives me a lot of troubles on forks, particularly in the damned manifest.
