### ISSUE TITLE
Transifex: No module named connection

### ISSUE THREAD

**Issue by guewen** [OCA/maintainer-quality-tools#523]
In oca/connector branches, we get this error in the transifex build:

```
$ if [ "$DOCS" != "1" ] ; then travis_run_tests; fi
======== Testing travis_transifex.py ========
No module named connection
```

ref: https://travis-ci.org/OCA/connector/jobs/327622845

Is it the only repository affected? Any idea?

**Comment by pedrobaeza** [comment]
It seems to be happening in all :dizzy_face: 

Maybe Transifex has changed something. I'm going to try to speed up Weblate adoption...

**Comment by pedrobaeza** [comment]
Fixed freezing transifex-client version: https://github.com/OCA/maintainer-quality-tools/commit/d7d2dc25ddd84a8c3efd712fb5a7bc81d3d2ffe8
