### ISSUE TITLE
Change eslint dot-location rule

### ISSUE THREAD

**Issue by Yajo** [OCA/maintainer-quality-tools#524]
Right now I have seen [these errors](https://travis-ci.org/OCA/report-print-send/jobs/327663308#L806-L809) for [these lines](https://github.com/OCA/report-print-send/blob/8b5c4f3fb05408d151de2566f6bad21f3d980976/base_report_to_printer/static/src/js/qweb_action_manager.js#L19-L20):

```
base_report_to_printer/static/src/js/qweb_action_manager.js:19: [W7903(javascript-lint), ] Expected dot to be on same line as object. [Error/dot-location]
```

Honestly, all my life I have used the inverse rule, which [should be `property` according to ESLint docs](https://eslint.org/docs/rules/dot-location#property). It also seems to be the common pattern along @OCA, so IMHO we should change it.

**Comment by moylop260** [comment]
@hugho-ad @lasley @oscarolar What do you think about?

**Comment by lasley** [comment]
Hmmmm yeah why is the linter defaulting to that? Who the hell does that?

I'm 👍  for the `property` option

**Comment by moylop260** [comment]
FYI https://github.com/OCA/pylint-odoo/pull/184
