### ISSUE TITLE
what is the pg_password value for the pgsql role 'travis' 

### ISSUE THREAD

**Issue by GoodERPJeff** [OCA/maintainer-quality-tools#532]
I need run a test for a backup script, we use PGDUMP in the script. and it need the os.environ['PGPASSWORD']  value to run pgdump

I guess travis container is running odoo with db_user = travis

but what is the db_password I can use ?

**Comment by StefanRijnhart** [comment]
Are you sure you need a password? See https://docs.travis-ci.com/user/database-setup/#Using-PostgreSQL-in-your-Builds

**Comment by pedrobaeza** [comment]
Closing as no answer.
