### ISSUE TITLE
Building wheels on travis

### ISSUE THREAD

**Issue by sbidoul** [OCA/maintainer-quality-tools#533]
While preparing to implement https://github.com/OCA/maintainer-tools/issues/331, I'm reviewing the current design of our mechanism to build and publish wheels.

One thing I'm considering is building the wheels on travis as part of `travis_after_tests_success`, with the benefits of:
* faster publishing (no need to wait for the current nightly batch)
* increased security (running setup.py in the travis sandbox)

After building, travis would need to rsync the artifacts to https://wheelhouse.odoo-community.org/oca-simple. That mechanism is very simple, but it requires a ssh key on travis side.

Adding the ssh key as a secret in the travis.yml of all existing and to be repos sounds like a lot of work (including when adding new repos), and I'm wondering if there is a simple solution for that that I would have overlooked.

Alternatively, we could keep the current design of building on the OCA server, and add a kind of webhook to trigger the builds. This approach requires no secret, but implies a more complex build server that knows which repos to build for, does the git fetch etc.

Any thoughts about this?

**Comment by elicoidal** [comment]
If I understand, you want to somehow leech on the Travis servers?
Do we need to check in the conditions whether there are some limitations?

**Comment by sbidoul** [comment]
@elicoidal I did not see it under that angle. Why do you call that leeching? Performing a build step is a quite common job for a CI infrastructure. Besides, the cost of that step is negligible compared to the tests we run.

**Comment by elicoidal** [comment]
@sbidoul :+1:  for me

**Comment by jbeficent** [comment]
+1 good point!

**Comment by pedrobaeza** [comment]
The problem is the technical challenge... I don't see right now how to do it. And if all the .travis.yml files have to be modified, then I prefer to add a build instead of using travis_after_success.

**Comment by sbidoul** [comment]
Yes indeed the challenge is to maintain the secrets in all .travis.yml files. @pedrobaeza did you have something automated to maintain the transifex secrets or was it manual?

**Comment by pedrobaeza** [comment]
Totally manually I'm afraid...
