### ISSUE TITLE
Limit the number of simultaneous builds on ansible-odoo

### ISSUE THREAD

**Issue by StefanRijnhart** [OCA/maintainer-quality-tools#534]
The ansible-odoo project currently has a matrix of 42 jobs. If it occupies all 5 available OCA job slots on Travis, it still keeps PRs from other projects waiting for more than 1.5 hours. Would you consider to limit the number of simultaneous slots for this project to, say, 2?

From https://blog.travis-ci.com/2014-07-18-per-repository-concurrency-setting: "... limit the number of concurrent builds on a per project bases..."

Cc @sebalix

**Comment by sebalix** [comment]
@StefanRijnhart I just saw that I have access to the Travis settings on this repo, I configured the 'Limit concurrent jobs' to 2.

**Comment by pedrobaeza** [comment]
I think we have to go repository per repository changing this value, isn't it?

**Comment by StefanRijnhart** [comment]
That's great @sebalix! @pedrobaeza I think it's only necessary if the project's Travis config spawns a lot of lengthy jobs such as this one. I don't know if there are any others but it won't be many.
