### ISSUE TITLE
Expected integrity errors are considered as test failures

### ISSUE THREAD

**Issue by asaunier** [OCA/maintainer-quality-tools#542]
When a test checks that an ``IntegrityError`` is actually raised using
```
with self.assertRaises(IntegrityError):
```
the quality tools incorrectly detects it as a test failure.

It seems related to that change in Odoo 9 months ago that makes an ``ERROR`` logged instead of ``INFO`` when an exception is raised while executing a DB query:
https://github.com/odoo/odoo/commit/c4e9b854ff22af31bbbd88d1414e77d27eaed7ea (see odoo/sql_db.py)

A workaround can be to prevent such errors from being logged by setting cursor's ``_default_log_exceptions`` to ``False``. See https://github.com/odoo/odoo/commit/e85f246469d6dbf5c9f801e20babd7d13b2c05f9

**Comment by pedrobaeza** [comment]
You have to use in that case the mute_logger decorator in the test.

**Comment by moylop260** [comment]
You can use
“with self.assert..., tools.mute_logger”


or 
@tools.mute_logger
def test_

**Comment by asaunier** [comment]
@pedrobaeza @moylop260 Thanks for the tip!
