### ISSUE TITLE
Disable lint W503 (break around binary operators) because doesn't conform PEP-8

### ISSUE THREAD

**Issue by luisg123v** [OCA/maintainer-quality-tools#552]
Lint W503 is triggered when a line break is before a binary operator, instead of being after, e.g.:
```
if (condition_1
        and condition_2):
```

However, PEP-8 has updated its position regarding this formatting, and it explicitly recommends quite the opposite, which is breaking before rather than after binary operators, like in the above example.

Therefore, the lint W503 should be disabled, because it goes against PEP-8 recomendations.

For more information, see:
https://github.com/PyCQA/pycodestyle/issues/498

**Comment by luisg123v** [comment]
CC @moylop260

**Comment by moylop260** [comment]
It was fixed from https://github.com/OCA/maintainer-quality-tools/pull/546

**Comment by luisg123v** [comment]
@moylop260 
As you can see in [This Travis](https://travis-ci.org/OCA/pylint-odoo/jobs/378007460#L699) from https://github.com/OCA/pylint-odoo/pull/196, the lint W503 is being triggered.

Doesn't it mean this is still valid? Sorry if I'm misunderstanding

**Comment by moylop260** [comment]
OCA/pylint-odoo is not using MQT project.
You can ignore these checks from travis.yml:
 - https://github.com/OCA/pylint-odoo/blob/7829e215cc40df3ac63fe5ded05b17f54740f5de/.travis.yml#L49
