### ISSUE TITLE
Pip breaks run tests

### ISSUE THREAD

**Issue by ovnicraft** [OCA/maintainer-quality-tools#557]
Runing my test with gitlab, i got this error:

```From https://github.com/odoo/odoo
 * branch            10.0       -> FETCH_HEAD
Collecting pip
  Downloading https://files.pythonhosted.org/packages/0f/74/ecd13431bcc456ed390b44c8a6e917c1820365cbebcb6a8974d1cd045ab4/pip-10.0.1-py2.py3-none-any.whl (1.3MB)
Installing collected packages: pip
  Found existing installation: pip 8.1.1
    Not uninstalling pip at /usr/lib/python2.7/dist-packages, outside environment /usr
Successfully installed pip-10.0.1
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    from pip import main
ImportError: cannot import name main
ERROR: Job failed: exit code 1
 ```

I read https://github.com/OCA/maintainer-quality-tools/blob/master/travis/travis_install_nightly#L97 and based on https://github.com/pypa/pip/issues/5240

consider as possible solutions:

* dont install pip from apt and install via curl
* upgrade pip with force-install

**Comment by pedrobaeza** [comment]
Sorry, but this has nothing to do with MQT. It's being used sucessfully in all Travis environments. Your Gitlab environment won't be correct.

**Comment by moylop260** [comment]
Did you tested the [gitlab-ci example](https://github.com/OCA/maintainer-quality-tools/blob/master/sample_files/.gitlab-ci.yml)?

**Comment by ovnicraft** [comment]
@moylop260 yes, i am using it
if you check this: https://github.com/OCA/maintainer-quality-tools/blob/master/sample_files/.gitlab-ci.yml#L32 you can reproduce the error

**Comment by ovnicraft** [comment]
@pedrobaeza Sorry but i am using gitlab-ci example from this repo and yaml file has deactivate TEST (linked in my previous comment) and its related not confirmed.

**Comment by moylop260** [comment]
Could you share your full .gitlab-ci file and the docker image that you are using?

**Comment by ovnicraft** [comment]
gitlab-ci file: https://gist.github.com/ovnicraft/c1fd582761f7e59720d4b7dff848f0eb

docker image is simple activated from gitlab-runner, what comes by default

**Comment by moylop260** [comment]
Currently, the MQT is supporting travis image
You can use a similar one from: https://hub.docker.com/r/vauxoo/odoo-80-image-shippable-auto
instead of default `image: ubuntu:16.04`
