### ISSUE TITLE
POT files are included by default in .gitignore files

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/maintainer-quality-tools#558]
@sbidoul with a new repository created from scratch with latest MQT template, POT files are ignored by default. Look the Travis log line:

https://travis-ci.org/OCA/data-protection/jobs/394475061#L797

I think it's correct to still keep the gitignore for avoiding manual changes on that files, but you should add to the script the force option for adding them on push.

**Comment by sbidoul** [comment]
Is it not weird to gitignore files that are managed by git?

**Comment by pedrobaeza** [comment]
Well, I think it's the best way to handle it:

- No change on existing repos with that .gitignore.
- No manual addition by accident of these files.
- Our script can handle this without problem.

**Comment by sbidoul** [comment]
Resolved at https://github.com/acsone/click-odoo-contrib/commit/d73c4dea44cc83e7845bde1bdb4de9d572932d12
