### ISSUE TITLE
Lint checks: bot commenting PR files

### ISSUE THREAD

**Issue by yelizariev** [OCA/maintainer-quality-tools#564]
I found this service for lint checks: https://houndci.com/

It would be good to activate it for OCA repositories. I also raised an issue to support pylint-odoo: https://github.com/houndci/hound/issues/1564
![bot](https://user-images.githubusercontent.com/186131/43353069-3337fa9e-9248-11e8-9e4e-647e5bcc0ccd.png)

**Comment by pedrobaeza** [comment]
Yeah, it can be a good idea, but it should allow custom configurations and pylint-odoo. We can put the more restrictive configuration as the one for being commented. The only problem I see is with the branches differences (for example, 11.0 has several lint checks that are the opposite of the rest of the branches - the coding comment -).

@moylop260 what do you think?

**Comment by moylop260** [comment]
LGTM
Do you know if we can customize lints?

**Comment by salbertson** [comment]
@yelizariev did you end up forking Hound to support Pylint? I'm curious to find out how it went.

**Comment by salbertson** [comment]
@yelizariev thanks! I think it's time Hound supported it.
