### ISSUE TITLE
[REF] allow install new wkhtmltopdf version 0.12.5

### ISSUE THREAD

**Issue by hugho-ad** [OCA/maintainer-quality-tools#572]
There is a new WebKit version https://github.com/wkhtmltopdf/wkhtmltopdf/releases/ but can't be installed passing WKHTMLTOPDF_VERSION var because name file changes and also the extensión now is a .deb instead of a .tar.xz
https://github.com/OCA/maintainer-quality-tools/blob/master/travis/travis_install_nightly#L131

Should update the WebKit installation options

**Comment by pedrobaeza** [comment]
What is the purpose of installing that version?

**Comment by hugho-ad** [comment]
In order update and try the fix of the issue [Memory limit too low or maximum file number of subprocess reached](https://github.com/odoo/odoo/issues/19160#issuecomment-393160785)

**Comment by pedrobaeza** [comment]
Yeah, but it's not needed in Travis builds (and on runbot for very few specific cases).

**Comment by hugho-ad** [comment]
IMHO Should mqt provide a way for those cases since the new version 0.12.5 is available.

Regards!

**Comment by pedrobaeza** [comment]
Well, it's interesting to have it, but not critical. If any contributes with the solution, I'll be glad to review it.
