### ISSUE TITLE
[Weblate] Line wrap perform on PO export

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/maintainer-quality-tools#581]
@sbidoul it seems that line wrapping is performed when Weblate exports PO files. This makes that any manual export of the PO will generate a huge diff when you have long lines, as Odoo doesn't perform that line wrapping. For being homogeneous, we should deactivate that wrapping. It seems there are support for that, according https://github.com/WeblateOrg/weblate/issues/365.

Do you know where can we activate that?

**Comment by sbidoul** [comment]
I don't know how it is configured.

OTOH, if we activate it, it will unwrap what is already wrapped.

I guess these huge diffs appear only on .po files coming out of transifex? So that issue will resolve itself progressively as existing .po files come to be managed by weblate?

**Comment by pedrobaeza** [comment]
> I guess these huge diffs appear only on .po files coming out of transifex? So that issue will resolve itself progressively as existing .po files come to be managed by weblate?

It's not something of Transifex, but of Odoo. If you add a new module and incorporates the translation exported from Odoo, it doesn't have line wrapping, but next time you touch the file on Weblate full file will be wrapped. The same happens with updated translations in PRs.

> OTOH, if we activate it, it will unwrap what is already wrapped.

No, it will only happen with files that have been touched in Weblate, not all. But letting this more time will raise the number of "wrapped" files.

**Comment by pedrobaeza** [comment]
@sbidoul what do you think about my reply? I have been searching where this can be selected, but I don't find it.

**Comment by sbidoul** [comment]
Personally, I'm not too worried about line wrapping.

Apparently that can be controlled with a weblate addon to tune the gettext options. That addon should then be enabled for each main component of each project.

**Comment by pedrobaeza** [comment]
Well, it's very annoying when you have long texts. Can you install that addon? And there's no option of defaulting to be enabled on new projects (although I can enable it for existing ones)?
