### ISSUE TITLE
New check: api.one on public methods

### ISSUE THREAD

**Issue by mreficent** [OCA/maintainer-quality-tools#588]
As explained in https://github.com/OCA/pylint-odoo/issues/237, there exists the warning `api-one-deprecated` for every method that use `@api.one` decorator.

But there exists a potential dangerous security problem if the method that use the `api.one` decorator is a **public** method. So I think a new check should be implemented, showing an **error** if a public method have the api.one decorator.

**Comment by mreficent** [comment]
@moylop260

**Comment by pedrobaeza** [comment]
The problem is not with `@api.one`, but exposing a method you don't want.

**Comment by mreficent** [comment]
But Odoo lately has been privatizing the public ones that still have api.one decorator.

**Comment by pedrobaeza** [comment]
But that are 2 unconnected things. Ivan said to you the same thing. They are doing that private because they don't want to expose that thing, not because they are `@api.one`.

**Comment by mreficent** [comment]
Well then, maybe it's just a coincidence that the methods privatized lately all have been with `@api.one`.

**Comment by sswapnesh** [comment]
> They are doing that private because they don't want to expose that thing,

Specially where sudo is used.
