### ISSUE TITLE
ImportError: No module named 'coverage

### ISSUE THREAD

**Issue by emagdalenaC2i** [OCA/maintainer-quality-tools#597]
I get the same warning as mentioned in #530 in a few PR I have just checked. See 

0.02s$ travis_after_tests_success
Traceback (most recent call last):
  File "/home/travis/maintainer-quality-tools/travis/travis_after_tests_success", line 5, in <module>
    from coverage.cmdline import main as coverage_main
ImportError: No module named 'coverage

**Comment by moylop260** [comment]
Maybe it is a error from installing process

Could you share us the URL of the travis-ci build log in order to see what happen in the step mentioned?

**Comment by emagdalenaC2i** [comment]
@moylop260 You can take a look in https://github.com/OCA/event/pull/142, here is the link to travis https://travis-ci.org/OCA/event/builds/517474054?utm_source=github_status&utm_medium=notification

And this is the message:
0.02s$ travis_after_tests_success
Traceback (most recent call last):
  File "/home/travis/maintainer-quality-tools/travis/travis_after_tests_success", line 5, in <module>
    from coverage.cmdline import main as coverage_main
ImportError: No module named 'coverage'

**Comment by moylop260** [comment]
Hi @emagdalenaC2i the url shared has a green status build
Then my hypothesis is confirmed.
It was a problem installing dependencies maybe a downtime of pypi or similar.
