### ISSUE TITLE
Enable downloadable tour failure screencasts and screenshots in v12

### ISSUE THREAD

**Issue by yajo** [OCA/maintainer-quality-tools#598]
Odoo 12 was born with a hidden feature that:

- If `--logfile` is passed to the command
- And `ffmpeg` is present
- And a tour fails

Prints a screenshot of the failed step and a screencast.

Tours are most integration-error-prone tests here at OCA. It would be great to have those.

**Comment by pedrobaeza** [comment]
@moylop260 do you think it's feasible? We can opt-in this behavior like we do with website dependencies through an environment variable.

**Comment by moylop260** [comment]
Do you like download a file from travis (where the tests are running)?
Travis doesn’t have access to download files of the build directly. (I think so)
Maybe, before to finish the build you can do a script to upload these kind of files to a particular server.

If you can upload any file to a particular server you will have the 90% of the issue solved.
Another 10% is just enable parameters and packages (If I understood fine)

**Comment by Yajo** [comment]
I'm seeing that [Travis supports uploading artifacts to S3 natively](https://docs.travis-ci.com/user/uploading-artifacts/), but not for pull requests. It has some security implications as explained in https://github.com/travis-ci/travis-ci/issues/5579.

Maybe a way to do this, for "free", and in pull requests, would be with our github bot. Steps:

1. Travis runs tests.
1. It outputs screenshots and screencasts as base64 strings.
1. When finished, the bot reads the logs and searches for them.
1. If found, the bot decodes those in files inside a zip that is uploaded to github as a comment attachment.

**Comment by pedrobaeza** [comment]
Maybe there's a Github app that allows that.

**Comment by moylop260** [comment]
@Yajo 
Your idea is so good using github bot.
For me: +1
