### ISSUE TITLE
.travis `LINT_CHECK` detects chardet as external dependency although it's on core

### ISSUE THREAD

**Issue by chienandalu** [OCA/maintainer-quality-tools#599]
When using `chardet` in a module, .travis detects it as an external dependency although it's already installed on Odoo core by `requests`, wich depends on it.

Example: https://travis-ci.org/OCA/l10n-spain/jobs/523518075#L913

**Comment by pedrobaeza** [comment]
It's not internal, so you have to declare it in `external_dependencies` I'm afraid. It's inherent to the way external dependencies are detected (through the import sentence).

**Comment by chienandalu** [comment]
Ok, thanks :)
