### ISSUE TITLE
Disabling C8101(manifest-required-author)

### ISSUE THREAD

**Issue by legalsylvain** [OCA/maintainer-quality-tools#611]
Hi all,

I'm using this tool for the CI of GRAP odoo repositories (incubator repositories).
I'm facing recently with a new error in the lint check
``product_simple_pricelist/__manifest__.py:5: [C8101(manifest-required-author), ] One of the following authors must be present in manifest: 'Odoo Community Association (OCA)'``

I'd like to use link check, but disable this check.

I don't know how to do it. Somebody has an idea ? 
Sorry if my question is not relevant.

Sample : https://travis-ci.org/grap/grap-odoo-incubator/jobs/587392718

CC : @sbidoul, @pedrobaeza

**Comment by legalsylvain** [comment]
I found a workaround to disable this check for my repository, addind command in my ``.travis.yml`` file.

```
install:
  - git clone --depth=1 https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  # Disable manifest-required-author for this repository
  - sed '/manifest-required-author,/d' ${HOME}/maintainer-quality-tools/travis/cfg/travis_run_pylint_pr.cfg -i
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly

**Comment by hbrunn** [comment]
that's one of two reasons why I use a clone of this in our CI: https://github.com/Therp/maintainer-quality-tools/commit/74dca161d20f81c3c70cb85cc83637065a780827 (the other is a custom jslint)

I tinkered a little bit with making this configurable via an environment variable or similar, but didn't find a convenient way to do it

**Comment by hbrunn** [comment]
how about adding the possibility to add a `.mqt.cfg` or similar to the repo's root which everyone can use to override stuff? Then also repos could have private rules for travis, which might or might not be a good thing to have.

**Comment by moylop260** [comment]
Currently, I'm using a wget command from .travis.yml
 - `wget URL_TO_MY_CONFIG_FILE -o ${HOME}/travis/cfg/travis_run_pylint_pr.cfg`
In order to overwrite the current one.

https://github.com/Vauxoo/pylint-conf/tree/master/conf

**Comment by moylop260** [comment]
In this case:

`wget https://raw.githubusercontent.com/Vauxoo/pylint-conf/master/conf/pylint_vauxoo_light_pr.cfg -o ${HOME}/maintainer-quality-tools/cfg/travis_run_pylint_pr.cfg`

**Comment by sbidoul** [comment]
For v13 we are moving to a solution based on pre-commit, where lint configuration files are copied to each repo and maintained up-to-date by the OCA bot. See also #613
