### ISSUE TITLE
Autopush .editorconfig to repos

### ISSUE THREAD

**Issue by Yajo** [OCA/maintainer-quality-tools#614]
Hi there!

First, a little bit of background:

- After https://github.com/OCA/maintainer-quality-tools/pull/613 was merged now we have a valid `.editorconfig` file: https://github.com/OCA/maintainer-quality-tools/blob/7190b984e4fc96216d667885aeaf9c84bae0ca52/sample_files/.editorconfig#L1-L30

- According to what @sbidoul said in https://github.com/OCA/maintainer-quality-tools/pull/613#issuecomment-537885747, all other new pre-commit files are autopushed to chosen module repo branches by the bot.

- The `.editorconfig` file was skipped because it wasn't announced nor discussed with the community before, as explained in https://github.com/OCA/maintainer-quality-tools/pull/613#issuecomment-541092172.

Well, here we are :grin:, let's discuss it. Should we push that file also to repos? If so, how? Is it a matter of just putting it in the pre-commit-13.0 folder? Otherwise having it there is useless... :roll_eyes: 

You can read what it's for in https://editorconfig.org, and how we came to it in https://github.com/acsone/maintainer-quality-tools/pull/1.

Thanks!

**Comment by pedrobaeza** [comment]
OK for me

**Comment by bealdav** [comment]
OK for me

**Comment by sbidoul** [comment]
Not: I suggest enumerating extensions for which OCA cares about editor configuration: e.g. `[*.{py,js,html,css,scss,less}]

> pre-commit files are autopushed

Not yet :) But I'm happy to push it manually to all branches (no reason to restrict this to 13.0).

**Comment by Yajo** [comment]
OK, do that please.

**Comment by bealdav** [comment]
Interesting subject.
Do you think that Odoo'll accept a .editorconfig file with only that ?
Who ping for know it ?

` trim_trailing_whitespace = true `

Then our editor might adapt its config according to the repo.

**Comment by pedrobaeza** [comment]
I think @xmo-odoo is the linter guardian of Odoo. Am I right?

**Comment by sbidoul** [comment]
BTW, does anyone now if runbot honors `[ci skip]`?

**Comment by pedrobaeza** [comment]
I think @moylop260 can answer that, and if not, we can do a pilot test in one branch to see

**Comment by bealdav** [comment]
Please @xmo-odoo, do you know if it's possible to add `.editorconfig` file to odoo source ?
Thanks

**Comment by xmo-odoo** [comment]
That's probably more @mart-e's thing than mine. I don't really care either way but given it would not do anything unless every other employee installed the relevant editor extension (as few use e.g. jetbains editors where it's built-in) I'm not sure it'd have much value.

Also hard pass on `trim_trailing_whitespace = true` considering its semantics, given
```
❯ rg --crlf -g '!**/static/lib' -g '!**/static/src/lib' '\s+$' ./odoo | wc -l
21150
```
Incidentally, indent=2 on rST also seems iffy given how weird its indents are, and how sensitive it is to proper indentation (plus wrong, if odoo has such a thing as a standard rST indent it's 4).

In fact that entire section seems misguided:
* rST see above
* yaml is gone
* to the extent that markdown has an indentation, 4 is pretty much the prescribed standard, according to the commonmark spec:
    - tabs expand to 4 spaces
    - indented code blocks are prefixed by 4+ spaces
    - list continuation items are indented by up to 4 spaces (exactly 4 in the original markdown), and ordered lists have to be indented by at least 3 spaces

    either way an indent of 2 for markdown seems... not very useful? The only place it'd get used is unordered lists where I'd expect markdown-aware editors to properly align continuation items with the corresponding list item

**Comment by bealdav** [comment]
cc @mart-e 

@xmo-odoo as said here https://github.com/OCA/maintainer-quality-tools/issues/614#issuecomment-543656284 the idea for odoo source is only this line

`trim_trailing_whitespace = false`

because odoo contains trailling space and not OCA, then we need a setting for each.

Thanks for your reply

**Comment by Yajo** [comment]
> Incidentally, indent=2 on rST also seems iffy given how weird its indents are, and how sensitive it is to proper indentation (plus wrong, if odoo has such a thing as a standard rST indent it's 4).

rst is weird indeed, but our most common use cases are order and unordered lists. For ordered, it's 3, and for unordered it's 2:

```
#. Ordered list
   3 spaces indent

* Unordered list.
  2 spaces indent
```

It's the same for MD, so I put 2 thinking that, at least, when you need 3 spaces you can hit <kbd>TAB</KBD><KBD>Space</kbd>, and when you need 4 you can use <kbd>TAB</KBD><kbd>TAB</KBD>

> yaml is gone

Yes, although we still use it in some places, such as `.travis.yml` or some people use `.gitlab-ci.yml` also. In any case, if you ever have to use a YAML file, you better indent it with 2 spaces, so it doesn't hurt there. We also maintain code for older versions that odoo, where YAML was used too.

> idea for odoo source is only this line
> 
> `trim_trailing_whitespace = false`
> 
> because odoo contains trailling space and not OCA, then we need a setting for each.

It'd be awesome, yes. I'm tired of repushing PRs to remove whitespace autocleanups.

> it would not do anything unless every other employee installed the relevant editor extension (as few use e.g. jetbains editors where it's built-in) I'm not sure it'd have much value.

Whoever doesn't use it, shouldn't care; and whoever uses it without knowledge, also. Whoever uses it will thank it.

**Comment by xmo-odoo** [comment]
> cc @mart-e
> 
> @xmo-odoo as said here [#614 (comment)](https://github.com/OCA/maintainer-quality-tools/issues/614#issuecomment-543656284) the idea for odoo source is only this line
> 
> `trim_trailing_whitespace = false`
> 
> because odoo contains trailling space and not OCA, then we need a setting for each.

Ah I see, so you'd want an editorconfig of 
```
[*] 
trim_trailing_whitespace = false 
```
in odoo?

**Comment by bealdav** [comment]
really yes ;-)

**Comment by moylop260** [comment]
@sbidoul 
> BTW, does anyone now if runbot honors [ci skip]?

Short Answer:
We have the following module: [runbot_subject_skip](https://github.com/OCA/runbot-addons/tree/11.0/runbot_subject_skip)
But it is working just for first line of the commit.

Large Answer:
I have created a PR to https://github.com/odoo/runbot in order to read the full multi-line commit message, but it was refused since that odoo people is not using this feature internally.
And creating an extra module to read the full multi-line commit message requires a big and ugly patch.

@gurneyalex 
Could we install this module in OCA runbot?

**Comment by sbidoul** [comment]
@moylop260 that's cool. First line is good enough.

**Comment by Yajo** [comment]
Let's continue in #616.
