### ISSUE TITLE
Reduce builds jobs to have lower build times?

### ISSUE THREAD

**Issue by dreispt** [OCA/maintainer-quality-tools#617]
We now have three jobs: lint, odoo and ocb.
In particular, the odoo and ocb jobs take a lot of time.
And IMO the duplication rarely bring value.

I suggest building against OCB only.
That would hopefully almost double our TravisCI builds.

**Comment by bealdav** [comment]
I'm completely all right with you about 
> I suggest building against OCB only.

for quickier jobs and to reduce environment impacts

**Comment by pedrobaeza** [comment]
First thing, on v13 there's a slight improvement: a pre-stage checks lint things and don't continue if error, which prevents a long answer in this case, but then the other 2 builds are done if this stage is succesful.

The reasoning behind doing both is for avoiding regressions introduced in OCB that are highlighted by the OCA modules. Deactivating one will keep us with the possible problem. This has happened barely once or 2 across the OCA history that I know, but...

**Comment by dreispt** [comment]
> This has happened barely once or 2 across the OCA history that I know, but...

My point precisely.
On the rare occasion this happens, we can change the PR to build against main Odoo and check.
And we also have cases where changes in other dependency repos break builds, so that would be nothing new.

**Comment by dreispt** [comment]
> First thing, on v13 there's a slight improvement: a pre-stage checks lint things and don't continue if error, which prevents a long answer in this case, but then the other 2 builds are done if this stage is succesful.

I think we setup a separate lint build precisely to allow running the tests, even if there were lint problems.
If if now prevents the tests from running, why not do everything in the same build , and exit early on lint errors?
The container setup for the lint also takes relevant time, consuming a build slot.

**Comment by pedrobaeza** [comment]
> On the rare occasion this happens, we can change the PR to build against main Odoo and check.

The problem is that we are not aware of that! If I only work on OCB, maybe Odoo is incompatible with my module because any specific change introduced there, or vice versa.

> I think we setup a separate lint build precisely to allow running the tests

Now it's a pre-requirement to have black passed (which is now our auto-linter), and nothing continues if so. That's why you install pre-commit in your local in few easy steps and it's checked each time you commit.

**Comment by sbidoul** [comment]
I think it is important to test against standard Odoo to avoid having OCA modules that take advantage of OCB patches and do not work on standard Odoo.

**Comment by lmignon** [comment]
I also thing it's important to test against standard Odoo. By curiosity... do we still need OCB (for 12.0 and 13.0)? Is OCB 12.0/13.0 different from Odoo 12.0/13.0?

**Comment by pedrobaeza** [comment]
Yes, they have a few patches already. Example: https://github.com/OCA/OCB/pull/884

**Comment by dreispt** [comment]
Valid points there.
TravisCI limits- wise, would if be any help consolidating the three build jobs into one?
(Are the limits per build or per job?)

**Comment by pedrobaeza** [comment]
I don't think it deserves the refactoring. The concurrent limit is by build, but it's the same to have 1 one longer build than 3 in parallel that release sooner.

**Comment by dreispt** [comment]
OK. Thanks.

**Comment by sbidoul** [comment]
What we could do is separate the Odoo and OCB jobs in separate stages, link we did for the lint stage in 13: since when they fail they tend to fail together, we could save one job in failure cases most of the time.

**Comment by pedrobaeza** [comment]
But that will mean to double the time to receive the result. I prefer not to do that.

**Comment by dreispt** [comment]
@pedrobaeza you also need to add the time for an available slot to start the build. If we can have shorter builds, when they fail, you will probably get builds started faster. The net effect might be positive.

**Comment by pedrobaeza** [comment]
I don't get your point... each job inside a build in independent, so if testing Odoo and OCB isolate takes 10 min per each, doing together will take 20 min. The net effect is that isolate it will return the result in 10 minutes (they are executed in parallel), and the second one will take 20.
