### ISSUE TITLE
[pre-commit] Conflict between black and flake8 (B950 line too long)

### ISSUE THREAD

**Issue by legalsylvain** [OCA/maintainer-quality-tools#621]
Hi all, 

i installed recently all the OCA pre-commit files in a new GRAP repository.
I'm facing some issue regarding max length. 

I wrote this line : 
```
            without_correct_partner_move_ids =\
                without_correct_partner_move_lines.mapped("move_id").ids
```

when running pre-commit, black is rewriting in 
```
            without_correct_partner_move_ids = without_correct_partner_move_lines.mapped(
                "move_id"
            ).ids
```

Then, flake8 is failing. 

```
my_module/models/my_file.py:141:90: B950 line too long (89 > 80 characters)
```

Did I missed something ? 
Did you faced same similar issues.

**Comment by bealdav** [comment]
black use 88 chars

**Comment by pedrobaeza** [comment]
With black, we disable that flake8 check and use instead a warning coming from bear. See the rest of the files with the configuration.

**Comment by legalsylvain** [comment]
> black use 88 chars

yes, but black is changing my code to create a line with 89 char.

> With black, we disable that flake8 check and use instead a warning coming from bear. See the rest of the files with the configuration.

I exactly use the OCA V13 configuration in my V12 repo  https://github.com/grap/grap-odoo-custom-account/ (I just changed manifest_required_authors value).

**Comment by pedrobaeza** [comment]
@sbidoul why this line still stands here:

https://github.com/grap/grap-odoo-custom-account/blob/12.0/.flake8#L2

although we talked about this?

**Comment by legalsylvain** [comment]
The original line is here : 

https://github.com/OCA/maintainer-quality-tools/blob/master/sample_files/pre-commit-13.0/.flake8#L2

**Comment by sbidoul** [comment]
The flake8 configuration is the one recommended in Black documentation (80 + occasional 10%).

@legalsylvain in rare cases black cannot find a solution that fits in 88 columns, you need to rework the code a little bit to help it.

**Comment by fuentes010** [comment]
>yes, but black is changing my code to create a line with 89 char.

Hi @legalsylvain 

We also face this issue and this is what [ black docs](https://black.readthedocs.io/en/stable/the_black_code_style.html#line-length) says about line length:
```
Black will try to respect that. However, sometimes it won’t be able to
without breaking other rules. In those rare cases, auto-formatted code 
will exceed your allotted limit.
```
In this case  you have to fix it by hand.

**Comment by pedrobaeza** [comment]
I remember talking about stepping down the line length to warning with something called bear or similar.

**Comment by sbidoul** [comment]
`flake8-bugbear` is already in place, that's why it does not complain until 88.
 We could change the value, but it's only postponing the problem.

**Comment by legalsylvain** [comment]
> @legalsylvain in rare cases black cannot find a solution that fits in 88 columns, you need to rework the code a little bit to help it.

OK. Thanks all. That's exactly my point. I had to rename my vars and that fixed the problem. 

kind regards.

**Comment by pedrobaeza** [comment]
Then seems clear, so closing.
