### ISSUE TITLE
pre-commit asking to add shebang in an xml file

### ISSUE THREAD

**Issue by LoisRForgeFlow** [OCA/maintainer-quality-tools#623]
I'm no sure if this is a misconfig in the checks for pre-commit or I really need to do something but I don't know what.

See the error I'm referring to: https://travis-ci.org/OCA/manufacture/jobs/626591643#L276.

```
mrp_multi_level/data/mrp_multi_level_cron.xml: marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: chmod -x mrp_multi_level/data/mrp_multi_level_cron.xml
  If it is supposed to be executable, double-check its shebang.
```

 Any clarification is welcomed. Thanks!

**Comment by pedrobaeza** [comment]
This is because you have a file with +x that shouldn't be, and it's specified in the log. Just do what is stated.

**Comment by LoisRForgeFlow** [comment]
TIL, git includes permissions of files :man_facepalming: 

Thanks Pedro!

**Comment by moylop260** [comment]
That hook looks similar to our pylint-odoo check: incoherent-interpreter-exec-perm

Year 2016
https://github.com/pre-commit/pre-commit-hooks/issues/99

Year 2015
https://github.com/OCA/pylint-odoo/pull/1

Now we will need deprecated duplicated checks in pylint-odoo that pre-commit has enabled.
