### ISSUE TITLE
Two modules dependant are not able to clarify in Travis which is mention in oca_dependencies

### ISSUE THREAD

**Issue by nikul-serpentcs** [OCA/maintainer-quality-tools#624]
I have an Added one module it's dependent on two other modules which is work in progress (Not merged yet).
When I Added external dependence on oca_dependencies file like
1. `operating-unit https://github.com/Dangar-Serpentcs/operating-unit 12.0-mig-res_partner_operating_unit`
2. `operating-unit https://github.com/BT-rmartin/operating-unit 12.0_product_operating_unit`

But OCA Runbot Got Error like this
![test 111](https://user-images.githubusercontent.com/17664321/71464675-4743ba80-27e0-11ea-9f82-008bfcf9f520.png)

**Comment by pedrobaeza** [comment]
oca_dependencies.txt is for other repositories, not for the same repository, so you can't do that. You have to wait until merged and then rebase, or include the commits of the other PRs in the dependent one, and when merged, rebase for removing them.
