### ISSUE TITLE
.isort.cfg is a conflicts bottleneck 

### ISSUE THREAD

**Issue by guewen** [OCA/maintainer-quality-tools#625]
In 13.0 projects, when we run pre-commit and an addon uses a new python lib, `seed-isort-config` will add the lib in the file `.isort.cfg` to list it as "known third party". Example of resulting file:

```
[settings]
; see https://github.com/psf/black
multi_line_output=3
include_trailing_comma=True
force_grid_wrap=0
combine_as_imports=True
use_parentheses=True
line_length=88
known_odoo=odoo
known_odoo_addons=odoo.addons
sections=FUTURE,STDLIB,THIRDPARTY,ODOO,ODOO_ADDONS,FIRSTPARTY,LOCALFOLDER
known_third_party=setuptools
```

This file is a huge contender for conflicts when working with unmerged pull requests and, for instance, we use gitaggregator to merge them together.

A real life example: PR https://github.com/OCA/stock-logistics-warehouse/pull/826 adds the `cubiscan` and `mock` libs, PR https://github.com/OCA/stock-logistics-warehouse/pull/797 adds `aiohttp`. On aggregation, we'll have a conflict such as:

```
diff --cc .isort.cfg
index 969be420,6bcf3847..00000000
--- a/.isort.cfg
+++ b/.isort.cfg
@@@ -9,4 -9,4 +9,10 @@@ line_length=8
  known_odoo=odoo
  known_odoo_addons=odoo.addons
  sections=FUTURE,STDLIB,THIRDPARTY,ODOO,ODOO_ADDONS,FIRSTPARTY,LOCALFOLDER
++<<<<<<< HEAD
 +known_third_party=aiohttp,setuptools
++||||||| 5ded73cf
++known_third_party=setuptools
++=======
+ known_third_party=cubiscan,mock,setuptools
++>>>>>>> e7f58dcdc68ccd1d53389b1fe03ec94a796f830c
```

Of course, conflicts between pull requests are not new and are inevitable, but we generally try to avoid them. The situation with `.isort.cfg` is painful though.

Is ordering the imports so important? (I find the whole `isort` "infrastructure" complex for the added value)

Thoughts?

**Comment by pedrobaeza** [comment]
I have also faced this and it's annoying, but not sure if there's a solution (except removing it).

@sbidoul you were the main creator of this, can you tell us?

**Comment by gurneyalex** [comment]
Can we have this isort.cfg automatically merged with gitattributes, as in https://github.com/OCA/delivery-carrier/pull/243/files (this one is fore oca_dependencies.txt, but it could be generalized)

**Comment by sbidoul** [comment]
I was going to write about gitattributes too. 

I wish isort would not need any configuration too.

**Comment by gurneyalex** [comment]
OTOH I'm not sure gitattributes will work, since the conflict is on a single line...

**Comment by guewen** [comment]
> Can we have this isort.cfg automatically merged with gitattributes, as in https://github.com/OCA/delivery-carrier/pull/243/files (this one is fore oca_dependencies.txt, but it could be generalized)

I thought about this, but the union merge driver takes the whole lines from the 2 versions, so AFAIU we would have:

```
known_third_party=aiohttp,setuptools
known_third_party=cubiscan,mock,setuptools
```

Even if `isort` is able to parse this (not sure?), I don't think [`seed-isort-config`](https://github.com/asottile/seed-isort-config/blob/master/seed_isort_config.py) can deal with it.

Git allows to use a custom script as merge driver, which would allow us to merge the actual content of the variable, but git does not allow to include this driver in `.git/config` (to prevent running arbitrary code on merges). The custom merge driver is then not a good solution.

**Comment by gurneyalex** [comment]
could we leave out the isort config file, and have the seeding script run before the travis tests?

**Comment by guewen** [comment]
> I wish isort would not need any configuration too.

Especially since `seed-isort-config` overwrites the value with the libs it finds on every commit, so it'd no be required to keep the list in a file if `isort` was doing the auto-detection of the libs on the fly. :cry:

**Comment by sbidoul** [comment]
maybe you can setup your gitaggregate config with a merge strategy that ignores .isort.cfg

If not possible with git-aggregator as is, here was an attempt that might be useful after all: https://github.com/acsone/git-aggregator/pull/20

**Comment by sbidoul** [comment]
The isort changelog has this sentence that might be interesting to investigate:

"Support for using requirements files to auto determine third-paty section if pipreqs & requirementslib are installed."

**Comment by guewen** [comment]
Great, I'll look into it. Another option is using https://github.com/asottile/reorder_python_imports instead of isort (to investigate)

**Comment by guewen** [comment]
> The isort changelog has this sentence that might be interesting to investigate:
> 
> "Support for using requirements files to auto determine third-paty section if pipreqs & requirementslib are installed."

I tried this here: https://github.com/OCA/stock-logistics-warehouse/pull/828

It works well on the use case I described. After aggregating my pull requests and using only `requirements.txt`, `isort` does not modify any files :fireworks:

**Comment by sbidoul** [comment]
This makes `requirements.txt` more important where I was kind of hoping it could be removed at some point. Which makes me think we can generate it: https://github.com/OCA/oca-github-bot/issues/98

**Comment by pedrobaeza** [comment]
Any news about this?

**Comment by pedrobaeza** [comment]
As a workaround, what about populating isort.cfg file with usual libraries in all repositories: setuptools, dateutil, etc.

I have needed to pre-add them in https://github.com/OCA/credit-control/commit/b45b27297df19f08dd657298e41d31464a271817 for avoiding conflicts in 4 simultaneous PRs to the same repo.

**Comment by sbidoul** [comment]
@pedrobaeza read from https://github.com/OCA/maintainer-quality-tools/pull/629#issuecomment-586732107 for the latest on this topic. Someone has to try @yajo's proposal first.
