### ISSUE TITLE
No so pretty XML formatting by prettier

### ISSUE THREAD

**Issue by sbidoul** [OCA/maintainer-quality-tools#632]
Example on mis_builder/report/mis_report_instance_qweb.xml

![image](https://user-images.githubusercontent.com/692075/74085630-24f9b980-4a7b-11ea-8696-114ccda16099.png)

@yajo WDYT ?

**Comment by Yajo** [comment]
Not so pretty indeed... I guess this is a risk with formatters.

How about opening the issue against https://github.com/prettier/plugin-xml?

Have you tested adding [ignore tags](https://github.com/prettier/prettier/blob/master/docs/ignore.md#html)?

**Comment by sbidoul** [comment]
https://github.com/prettier/plugin-xml/issues/40 addresses this.

So we probably need to add `xmlWhitespaceSensitivity: ignore` in `.prettierrc.yml` to let it indent correctly (i.e. when there is whitespace only between tags).
