### ISSUE TITLE
Handle OERPScenario tests

### ISSUE THREAD

**Issue by gurneyalex** [OCA/maintainer-quality-tools#66]
Related to https://github.com/OCA/account-financial-tools/pull/16

What needs to be done:

* no triggering of flake8 false positives on oerpscenario step definition code
* run the oerpscenario tests of the addons, if any

**Comment by dreispt** [comment]
This is quite idle. Maybe we can close it and reopen when new efforts on it are possible.

**Comment by pedrobaeza** [comment]
As this has not been used and no interest in a while, I close. Anyone interested can raise the issue again.
