### ISSUE TITLE
Doodba based alternative for travis

### ISSUE THREAD

**Issue by yelizariev** [OCA/maintainer-quality-tools#670]
https://github.com/itpp-labs/DINAR/

It should solve following concerns of travis and MQT:

* MQT is not designed to be reusable in non-OCA repos
* MQT+travis don't use cache, for example ``point_of_sale`` module is installed on every build in OCA/pos repo
* Travis build environment cannot be easily reproduced locally (imagine that travis shows tests error, which you don't have locally)
* Doodba ecostystem is not used,  some part of MQT scripts can be replaced with Doodba
* No support for [git-aggregator](https://github.com/acsone/git-aggregator)

Bonus:
* DINAR has script to propagate created or changed files to all repositories

Roadmap:
* dockers generated by DINAR could be used by a tool for modules preview (something like runbot, but more customizable, e.g. to have a build with one module installed only)

**Comment by pedrobaeza** [comment]
I support totally this idea and IMO we have a very heavy layer for testing (Travis) + trying (runbot) currently on OCA.

**Comment by Yajo** [comment]
Maybe you should consider adding the required configs to https://github.com/OCA/oca-addons-repo-template

**Comment by yelizariev** [comment]
That would not be easy... First thing to do is adding this Github Action, which create doodba images for a repo https://github.com/itpp-labs/DINAR/blob/master/static-files/all/.github/workflows/DINAR.yml

What would be proper places for scripts used in the github action (search for ``DINAR/workflow-files`` in the link above)?

**Comment by Yajo** [comment]
The link above is a copier template, pretty much like https://github.com/Tecnativa/doodba-copier-template (I guess you more-or-less know how copier templates work, because you already contributed there), so you can drop in the files where they should land in the final addons repo.

**Comment by yelizariev** [comment]
yes, I understand. My idea is to don't have scripts copy in every repo if it may be stored in a single place

**Comment by Yajo** [comment]
AFAIK, github workflows must be written repo by repo always, as a requirement by github itself, so using the template seems to be the best option here. Also, there's going to be a automatism that updates repos when a new template is released.

Otherwise it'd have to be on https://github.com/OCA/oca-github-bot, but I think that targets automated actions, not status checks or runbots...

**Comment by rvalyi** [comment]
I'm closing this one as the github workflows have been implemented to replace Travis,
