### ISSUE TITLE
How can i add enterprise repository?

### ISSUE THREAD

**Issue by raulovallet** [OCA/maintainer-quality-tools#671]
I try add odoo enterprise repository becase my module depends of one app from odoo enterprise and I get this error:

<img width="811" alt="Screen Shot 2020-06-26 at 11 41 00 AM" src="https://user-images.githubusercontent.com/23384474/85880619-eb171e80-b7a1-11ea-90f1-734d85a788ad.png">

I understand that it must be something of permissions, somebody could help me like giving permissions to travis for odoo enterprice?

**Comment by moylop260** [comment]
You are cloning a private repository using a public URL.
It is not a MQT issue.
You should looking for from travis itself.
