### ISSUE TITLE
modules importing werkzeug end with a red build

### ISSUE THREAD

**Issue by gurneyalex** [OCA/maintainer-quality-tools#674]
If I import werkzeug in my module, I get a red build:

https://travis-ci.org/github/OCA/rest-framework/jobs/717927005#L382

I expect this to not be an error as werkzeug is a dependency of Odoo.

**Comment by gaikaz** [comment]
I don't know if `werkzeug` is just an example here, but I'm pretty sure the same happens with `num2words`.
Haven't checked with the newest pre-commit configs but I suppose this is a general convenience issue.

**Comment by gurneyalex** [comment]
@moylop260  do you have any insight on this?

**Comment by sbidoul** [comment]
@gurneyalex this was probably resolved in https://github.com/OCA/pylint-odoo/pull/283.
I upgraded pylint-odoo in https://github.com/OCA/rest-framework/pull/74 and https://github.com/OCA/rest-framework/pull/75.

**Comment by sbidoul** [comment]
The 12.0 branch of rest-framework is now green, so I propose to close this.
