### ISSUE TITLE
Add development-status-allowed mandatory check

### ISSUE THREAD

**Issue by sbidoul** [OCA/maintainer-quality-tools#679]
See also https://github.com/OCA/oca-addons-repo-template/pull/27

**Comment by dreispt** [comment]
For information: this issue is preventing some modules from being published at https://odoo-community.org/shop

**Comment by sbidoul** [comment]
@moylop260 can you help here? I never remember in which file to add such config.

**Comment by moylop260** [comment]
Yes, Of course
 - https://github.com/OCA/maintainer-quality-tools/pull/680

**Comment by sbidoul** [comment]
Thanks @moylop260
