### ISSUE TITLE
python 3.8 compatibility issues

### ISSUE THREAD

**Issue by t-900-a** [OCA/maintainer-quality-tools#682]
It seems I'm getting compatibility errors with python 3.8 and flake8.
The base of my project is copied from this repo.

The error:
AttributeError: 'FlakesChecker' object has no attribute 'CONSTANT'

Example failing job:
https://travis-ci.com/github/t-900-a/moneroodoo/jobs/459043217

Commits: https://github.com/t-900-a/moneroodoo/commits/main

Resolution:
I'm not sure how to resolve this, I don't see a flake8 version being specified specifically

**Comment by t-900-a** [comment]
> 
> 
> And isn't something of flake8, not here?

When I run flake8 locally I don't run into this issue. That's why I believe it may have to do with this repo's configuration. I'm using version flake8 3.8.4 and python 3.8.5.

Is the flake8 version specified in this repo? I don't see it being specified.

**Comment by sbidoul** [comment]
I don't think we'll ever make this repo compatible with python 3.8. Please see https://github.com/oca/oca-addons-repo-template for the latest OCA linter configurations.
