### ISSUE TITLE
Wrong Version Format "13.0.x.x.x" in manifest file when migrating modules to 14.0

### ISSUE THREAD

**Issue by StefanRijnhart** [OCA/maintainer-quality-tools#684]
https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-14.0 says to apply pre-commit before module migration, but this triggers `manifest-version-format` from `.pylintrc-mandatory`.

What is the best way to go about this?

**Comment by pedrobaeza** [comment]
That's not really a problem, as the error is shown, but the goal of running `pre-commit run -a` is to have black/prettier/isort formatting done, which certainly does. Then you commit with `--no-verify` option for avoiding such thing to prevent the block.

**Comment by StefanRijnhart** [comment]
Thanks!

**Comment by StefanRijnhart** [comment]
Can I add a comment about this in the migration manual on the wiki?

**Comment by pedrobaeza** [comment]
Yes, what are you thinking about?

**Comment by StefanRijnhart** [comment]
Sorry, it already says `ignore pylint errors at this stage`. I never read through to the end of the line :man_facepalming:
