### ISSUE TITLE
Missing ability to install postgresql extention on database

### ISSUE THREAD

**Issue by nbessi** [OCA/maintainer-quality-tools#69]
There is no hook to allows to run some command after database creation or at least to deactivate database creation:

For geospatial addons I need to run:

    createdb openerp_test
    psql -U postgres -c "create extension postgis" openerp_test

**Comment by bwrsandman** [comment]
@nbessi How is the issue?

Can we close this?

**Comment by nbessi** [comment]
Yes it worked and with new Postgresql version no more need to do it.
