### ISSUE TITLE
Organization level issue templates

### ISSUE THREAD

**Issue by joao-p-marques** [OCA/maintainer-quality-tools#692]
Github allows to define a set of issue templates in a repository. One of the advantages of this is limiting and filtering the amount and type of questions that land in the issue tracker.

These templates can also be set at an organization level, by opening a repository named `OCA/.github`, and all the files there would be shared across all OCA repos (See https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file).

So, for example, to easily create a template to only allow **bug reports** and **feature requests**, we would only need to open that repo with the following files and respective content:
`.github/ISSUE_TEMPLATE/bug_report.md`:
```md
---
name: Bug report
about: Report a bug
title: ""
labels: bug
assignees: ""
---

<!-- Provide a general summary of the issue in the Title above.
Before opening the issue, please check that there isn't another issue addressing the same problem already created -->

## Describe the bug 
A clear and concise description of what the bug is.

## To Reproduce
**Affected versions**:

Steps to reproduce the behavior:
1. 
2. 
3.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Additional context**
Add any other context about the problem here. (e.g. OS, Python version, ...)
```

`.github/ISSUE_TEMPLATE/feature_request.md`:
```md
---
name: Feature request
about: Suggest an idea for this project
title: ""
labels: enhancement
assignees: ""
---

**Is your feature request related to a problem?**
If so, please provide clear and concise description of what the problem is.

**Describe the solution you'd like**
A clear and concise description of what you want to happen.

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered.

**Additional context**
Add any other context about the feature request here.
```

`ISSUE_TEMPLATE/config.yml`:
```yaml
blank_issues_enabled: false
```

To add another category for general questions, we can provide a link to an external platform (like Discord, etc.) by adding the following key to the `config.yml` file:
```yaml
contact_links:
  - name: Question or general talk
    url: SOME_URL
    about: Please ask and answer questions here.
```

Obviously, these can all be changed according to preference, and a lot of other common configurations (e.g. CONTRIBUTING and CODE_OF_CONDUCT) can also be kept here.

If these need to be changed on a repo level, we can simply create those files there, and they will override this general config.

ping @pedrobaeza

**Comment by pedrobaeza** [comment]
It's a very good idea and we can discuss about the content of the templates, but I think it should be put. The blocking point for putting this before was the need of doing it repo per repo/branch per branch, but a global one is great.

@sbidoul @dreispt @simahawk do you proceed with the creation of the repo `OCA/.github` and then we discuss the content in the PR adding the files?

**Comment by simahawk** [comment]
Good idea! The repo it's already available https://github.com/OCA/.github :wi

**Comment by joao-p-marques** [comment]
Thanks! I already opened a PR with the first version of the Bug Reports and Feature Request messages suggested above: https://github.com/OCA/.github/pull/1

**Comment by pedrobaeza** [comment]
This is already done, isn't it? So this should be closed.
