### ISSUE TITLE
ERROR: No matching distribution found for QUnitSuite

### ISSUE THREAD

**Issue by rvalyi** [OCA/maintainer-quality-tools#704]
Hello, for the repos running the old Travis tests like v12,
the travis_install_nightly script tries to install `pip install -q QUnitSuite`
https://github.com/OCA/maintainer-quality-tools/blob/master/travis/travis_install_nightly#L117
But sadly since a coupe of days this doesn't work anymore and we get this error:
https://app.travis-ci.com/github/OCA/l10n-brazil/jobs/568612311#L419
You can try yourself with Python 2 or Python 3:
```
python -m pip install -q QUnitSuite
ERROR: Could not find a version that satisfies the requirement QUnitSuite (from versions: none)
ERROR: No matching distribution found for QUnitSuite
```

it's not on pypi either...

is it used at all? or can we simply remove it from https://github.com/OCA/maintainer-quality-tools/blob/master/travis/travis_install_nightly#L117 may be??

cc @marcelsavegnago

**Comment by pedrobaeza** [comment]
It can be used for UI tests that are in QUnit. Hardly none OCA modules is using it, but this being a general tooling, we should provide an alternative. What has happened to such package?

**Comment by rvalyi** [comment]
FYI, we used this in OCA/l10n-brazil to keep merging until this is sorted out https://github.com/OCA/l10n-brazil/commit/7e3876add1660a75f9d0fa451b7cff359ebd20a4

**Comment by jfernandez-busman** [comment]
I have been told by the maintainers the library is up again (They have uploaded it as a new version)

**Comment by pedrobaeza** [comment]
Yeah, I confirm now it works in https://github.com/OCA/l10n-spain/pull/2229
