### ISSUE TITLE
eslint error: Parsing error: 'import' and 'export' may appear only with 'sourceType: module'

### ISSUE THREAD

**Issue by gurneyalex** [OCA/maintainer-quality-tools#714]
We encountered this error on

* https://github.com/OCA/web/pull/2408
* https://github.com/OCA/knowledge/pull/363

It seems to be related to https://github.com/AtomLinter/linter-eslint/issues/462 and requires an update to the eslint configuration in the pre-commit config (see this comment: https://github.com/AtomLinter/linter-eslint/issues/462#issuecomment-190770417)

**Comment by santostelmo** [comment]
Naming js file like `*.esm.js` it will fix that. 
https://github.com/OCA/oca-addons-repo-template/blob/205a74777bbbffa6ee68d55ec9aec8f724bdd882/src/%7B%25%20if%20odoo_version%20%3E%2012%20%25%7D.eslintrc.yml%7B%25%20endif%20%25%7D#L11
