### ISSUE TITLE
Quality Tools Releases 1 and 2 Announcement

### ISSUE THREAD

**Issue by dreispt** [OCA/maintainer-quality-tools#86]
Acknowledging the different repositories (and branches) might be in different quality maturity levels, it has been decided to implement "releases" for the Quality Tools. (See #84 for details).

Each repository branch can pick the release to use, according to it's specific maturity and needs.Currently we have three available releases:

  - **r1**: dates from 23/July, and is the last version allowing lines up to 120 characters.
  - **r2**: dates from today (9/Sep), has lines limited to 79 chars, has better coverage measurements, and supports INCLUDE and EXCLUDE directives.
  - **master**: is where the most recent additions to quality checks will be merged, such as better linting.

A "release" is just a branch of the OCA/maintainer-quality-tools, so they can evolve, but mostly to include fixes. Currently all repositories are using `master`. To pick a specific release, just add `-b` option to the `git clone` in the `.travis.yml`. For example:

    git clone https://github.com/OCA/maintainer-quality-tools.git $HOME/maintainer-quality-tools -b r2

We will keep on hold for a few days the pending pull requests, to allow changes to be done on the relevant projects.

Whenever we feel additional checks could be included, that could have significant impact on existing repositories, we will consider a release 3 "stability point" and announce upcoming changes it in advance.

Any questions or suggestions for this process, this is also the place to ask and discuss.
Even if not interested in watching this repository discussions, it is advised to subscribe this Issue to learn about any changes in releases.

**Comment by pedrobaeza** [comment]
Are realeases still interesting?

**Comment by moylop260** [comment]
IMHO with new stable, beta, pr and version-exclude configuration files is supported release.
And now with coverage 89% and pr dummy to self-test now the changes are more stables.
We could close this issue
